
class CategoryK {
    static Map<String, String> categoryK = {
        "K": "(K is from the Latin, which used the letter but little exceptin the early period of the language. It came into the Latin from theGreek, which received it from a Phoenician source, the ultimateorigin probably being Egyptian,. Etymologically K is most nearlyrelated to c, g, h (which see).",
        "KAAMA": "The hartbeest.",
        "KABALA": "See Cabala.",
        "KABASSOU": "See Cabassou.",
        "KABOB": "See Cabob, n. & v. t.",
        "KABOOK": "A clay ironstone found in Ceylon.",
        "KABYLE": "A Berber, as in Algiers or Tunis. See Berber.",
        "KADDER": "The jackdaw.",
        "KAFAL": "The Arabian name of two trees of the genus Balsamodendron,which yield a gum resin and a red aromatic wood.",
        "KAFFLE": "See Coffle.",
        "KAFILAH": "See Cafila.",
        "KAFTAN": "See Caftan.",
        "KAGE": "A chantry chapel inclosed with lattice or screen work.",
        "KAGU": "A singular, crested, grallatorial bird (Rhinochetos jubatus),native of New Caledonia. It is gray above, paler beneath, and thefeathers of the wings and tail are handsomely barred with brown,black, and gray. It is allied to the sun bittern.",
        "KAGUAN": "The colugo.",
        "KAHANI": "A kind of notary public, or attorney, in the Levant.",
        "KAHAU": "A long-nosed monkey (Semnopithecus nasalis), native of Borneo.The general color of the body is bright chestnut, with the underparts, shoulders, and sides of the head, golden yellow, and the topof the head and upper part of the back brown. Called also proboscismonkey. [Written also kaha.]",
        "KAIL": "A kind of headless cabbage. Same as Kale, 1.",
        "KAIMACAM": "Same as Caimacam.",
        "KAIN": "Poultry, etc., required by the lease to be paid in kind by atenant to his landlord. Wharton (Law Dict.).",
        "KAINIT": "Salts of potassium used in the manufacture of fertilizers.",
        "KAINITE": "A compound salt consisting chiefly of potassium chloride andmagnesium sulphate, occurring at the Stassfurt salt mines in PrussianSaxony.",
        "KAINOZOIC": "See Cenozoic.",
        "KAIQUE": "See Caique.",
        "KAIRINE": "A pale buff or white crystalline alkaloid derived fromquinoline, and used as an antipyretic in medicine.",
        "KAIROLINE": "An organic base obtained from quinoline. It is used as afebrifuge, and resembles kairine.",
        "KAISER": "The ancient title of emperors of Germany assumed by KingWilliam of Prussia when crowned sovereign of the new German empire in1871.",
        "KAKA": "A New Zealand parrot of the genus Nestor, especially the brownparrot (Nestor meridionalis).",
        "KAKAPO": "A singular nocturnal parrot (Strigops habroptilus), native ofNew Zealand. It lives in holes during the day, but is active atnight. It resembles an owl in its colors and general appearance. Ithas large wings, but can fly only a short distance. Called also owlparrot, night parrot, and night kaka.",
        "KAKARALLI": "A kind of wood common in Demerara, durable in salt water,because not subject to the depredations of the sea worm and barnacle.",
        "KAKISTOCRACY": "Government by the worst men.",
        "KAKOXENE": "See Cacoxene.",
        "KALAN": "The sea otter.",
        "KALASIE": "A long-tailed monkey of Borneo (Semnopithecus rubicundus). Ithas a tuft of long hair on the head.",
        "KALE": "A variety of cabbage in which the leaves do not form a head,being nearly the original or wild form of the species. [Written alsokail, and cale.]",
        "KALEEGE": "One of several species of large, crested, Asiatic pheasants,belonging to the genus Euplocamus, and allied to the firebacks.",
        "KALEIDOSCOPE": "An instrument invented by Sir David Brewster, which containsloose fragments of colored glass, etc., and reflecting surfaces soarranged that changes of position exhibit its contents in an endlessvariety of beautiful colors and symmetrical forms. It has been muchemployed in arts of design.Shifting like the fragments of colored glass in the kaleidoscope. G.W. Cable.",
        "KALENDAR": "See Calendar.",
        "KALENDARIAL": "See Calendarial.",
        "KALENDER": "See 3d Calender.",
        "KALENDS": "Same as Calends.",
        "KALI": "The last and worst of the four ages of the world; -- consideredto have begun B. C. 3102, and to last 432,000 years.",
        "KALIF": "See Caliph.",
        "KALIFORM": "Formed like kali, or glasswort.",
        "KALIGENOUS": "Forming alkalies with oxygen, as some metals.",
        "KALIUM": "Potassium; -- so called by the German chemists.",
        "KALKI": "The name of Vishnu in his tenth and last avatar. Whitworth.",
        "KALMIA": "A genus of North American shrubs with poisonous evergreenfoliage and corymbs of showy flowers. Called also mountain laurel,ivy bush, lamb kill, calico bush, etc.",
        "KALMUCK": "See Calmucks.",
        "KALONG": "A fruit bat, esp. the Indian edible fruit bat (Pteropusedulis).",
        "KALOYER": "See Caloyer.",
        "KALPA": "One of the Brahmanic eons, a period of 4,320,000,000 years. Atthe end of each Kalpa the world is annihilated.",
        "KALSOMINE": "Same as Calcimine.",
        "KAM": "Crooked; awry. [Obs.] \"This is clean kam.\" Shak.",
        "KAMA": "The Hindoo Cupid. He is represented as a beautiful youth, witha bow of sugar cane or flowers.",
        "KAMALA": "The red dusty hairs of the capsules of an East Indian tree(Mallotus Philippinensis) used for dyeing silk. It is violentlyemetic, and is used in the treatment of tapeworm. [Written alsokameela.]",
        "KAME": "A low ridge. [Scot.] See Eschar.",
        "KAMI": "A title given to the celestial gods of the first mythicaldynasty of Japan and extended to the demigods of the second dynasty,and then to the long line of spiritual princes still represented bythe mikado.",
        "KAMICHI": "A curious South American bird (Anhima, or Palamedea, cornuta),often domesticated by the natives and kept with poultry, which itdefends against birds of prey. It has a long, slender, hornlikeornament on its head, and two sharp spurs on each wing. Although itsbeak, feet, and legs resemble those of gallinaceous birds, it isrelated in anatomical characters to the ducks and geese (Anseres).Called also horned screamer. The name is sometimes applied also tothe chaja. See Chaja, and Screamer.",
        "KAMPTULICON": "A kind of elastic floor cloth, made of India rubber, gutta-percha, linseed oil, and powdered cork.",
        "KAMPYLITE": "A variety of mimetite or arseniate of lead in hexagonal prismsof a fine orange yellow. [Written also campylite.]",
        "KAMTSCHADALES": "An aboriginal tribe inhabiting the southern part ofKamtschatka.",
        "KAN": "To know; to ken. [Obs.] See Ken.",
        "KANCHIL": "A small chevrotain of the genus Tragulus, esp. T. pygmæus, orT. kanchil, inhabiting Java, Sumatra, and adjacent islands; adeerlet. It is noted for its agility and cunning.",
        "KAND": "Fluor spar; -- so called by Cornish miners.",
        "KANGAROO": "Any one of numerous species of jumping marsupials of the familyMacropodidæ. They inhabit Australia, New Guinea, and adjacentislands, They have long and strong hind legs and a large tail, whilethe fore legs are comparatively short and feeble. The giant kangaroo(Macropus major) is the largest species, sometimes becoming twelve orfourteen feet in total length. The tree kangaroos, belonging to thegenus Dendrolagus, live in trees; the rock kangaroos, of the genusPetrogale, inhabit rocky situations; and the brush kangaroos, of thegenus Halmaturus, inhabit wooded districts. See Wallaby.",
        "KANSAS": "A tribe of Indians allied to the Winnebagoes and Osages. Theyformerly inhabited the region which is now the State of Kansas, butwere removed to the Indian Territory.",
        "KANTIAN": "Of or pertaining to Immanuel Kant, the German philosopher;conformed or relating to any or all of the philosophical doctrines ofImmanuel Kant.",
        "KANTIST": "A disciple or follower of Kant.",
        "KANTTRY": "Same as Cantred.",
        "KAOLINIZATION": "The process by which feldspar is changed into kaolin.",
        "KAOLINIZE": "To convert into kaolin.",
        "KAPELLE": "A chapel; hence, the choir or orchestra of a prince's chapel;now, a musical establishment, usually orchestral. Grove.",
        "KAPELLMEISTER": "See Capellmeister.",
        "KAPIA": "The fossil resin of the kauri tree of New Zealand.",
        "KAPNOMAR": ") See Capnomor.",
        "KAPOK": "A silky wool derived from the seeds of Ceiba pentandra (syn.Eriodendron anfractuosum), a bombaceous tree of the East and WestIndies.",
        "KARAGANE": "A species of gray fox found in Russia.",
        "KARAISM": "Doctrines of the Karaites.",
        "KARAITE": "A sect of Jews who adhere closely to the letter of theScriptures, rejecting the oral law, and allowing the Talmud nobinding authority; -- opposed to the Rabbinists.",
        "KARAKUL": "Astrakhan, esp. in fine grades. Cf. Caracul.",
        "KARATAS": "A West Indian plant of the Pineapple family (NidulariumKaratas).",
        "KARMA": "One's acts considered as fixing one's lot in the futureexistence. (Theos.) The doctrine of fate as the inflexible result ofcause and effect; the theory of inevitable consequence.",
        "KARMATHIAN": "One of a Mohammedan sect founded in the ninth century byKarmat.",
        "KARN": "A pile of rocks; sometimes, the solid rock. See Cairn.",
        "KAROB": "The twenty-fourth part of a grain; -- a weight used bygoldsmiths. Crabb.",
        "KAROSS": "A native garment or rug of skin sewed together in the form of asquare. [South Africa]",
        "KARPHOLITE": "A fibrous mineral occurring in tufts of a straw-yellow color.It is a hydrous silicate of alumina and manganese.",
        "KARROO": "One of the dry table-lands of South Africa, which often riseterracelike to considerable elevations. [Also karoo.] The GreatKarroo, or The Karroo, a vast plateau, in Cape Colony, stretchingthrough five degrees of longitude, at an elevation of about 3,000feet.",
        "KARSTENITE": "Same as Anhydrite.",
        "KARVEL": "See Carvel, and Caravel.",
        "KARYOKINESIS": "The indirect division of cells in which, prior to division ofthe cell protoplasm, complicated changes take place in the nucleus,attended with movement of the nuclear fibrils; -- opposed tokaryostenosis. The nucleus becomes enlarged and convoluted, andfinally the threads are separated into two groups which ultimatelybecome disconnected and constitute the daughter nuclei. Called alsomitosis. See Cell development, under Cell.",
        "KARYOKINETIC": "Of or pertaining to karyokinesis; as, karyokinetic changes ofcell division.",
        "KARYOMITON": "The reticular network of fine fibers, of which the nucleus of acell is in part composed; -- in opposition to kytomiton, or thenetwork in the body of the cell. W. Flemming.",
        "KARYOPLASMA": "The protoplasmic substance of the nucleus of a cell:nucleoplasm; -- in opposition to kytoplasma, the protoplasm of thecell.",
        "KARYOSTENOSIS": "Direct cell division (in which there is first a simple divisionof the nucleus, without any changes in its structure, followed bydivision of the protoplasm of the karyostenotic mode of nucleardivision.",
        "KARYOSTENOTIC": "Pertaining to, or connected with, karyostenosis; as, thekaryostenotic mode of nuclear division.",
        "KASACK": "Same as Cossack.",
        "KAT": "An Arabian shrub Catha edulis) the leaves of which are used astea by the Arabs.",
        "KATABOLIC": "Of or pertaining to katabolism; as, katabolic processes, whichgive rise to substances (katastates) of decreasing complexity andincreasing stability.",
        "KATABOLISM": "Destructive or downward metabolism; regressive metamorphism; --opposed to anabolism. See Disassimilation.",
        "KATASTATE": "(Physiol.) A substance formed by a katabolic process; --opposed to anastate. See Katabolic.",
        "KATE": "The brambling finch.",
        "KATHETAL": "Making a right angle; perpendicular, as two lines or two sidesof a triangle, which include a right angle.",
        "KATHETOMETER": "Same as Cathetometer.",
        "KATTIMUNDOO": "A caoutchouc like substance obtained from the milky juice ofthe East Indian Euphorbia Kattimundoo. It is used as a cement.",
        "KATYDID": "A large, green, arboreal, orthopterous insect (Cyrtophyllusconcavus) of the family Locustidæ, common in the United States. Themales have stridulating organs at the bases of the front wings.During the summer and autumn, in the evening, the males make apeculiar, loud, shrill sound, resembling the combination Katy-did,whence the name.",
        "KAURI": "A lofty coniferous tree of New Zealand Agathis, or Dammara,australis), furnishing valuable timber and yielding one kind ofdammar resin. [Written also kaudi, cowdie, and cowrie.]",
        "KAVA": "A species of Macropiper (M. methysticum), the long pepper, fromthe root of which an intoxicating beverage is made by thePolynesians, by a process of mastication; also, the beverage itself.[Written also kawa, kava, and ava.]",
        "KAVASS": "An armed constable; also, a government servant or courier.[Turkey]",
        "KAW": "See Caw.",
        "KAWAKA": "a New Zealand tree, the Cypress cedar (Libocedrus Doniana),having a valuable, fine-grained, reddish wood.",
        "KAWN": "A inn. [Turkey] See Khan.",
        "KAYAK": "A light canoe, made of skins stretched over a frame, andusually capable of carrying but one person, who sits amidships anduses a double-bladed paddle. It is peculiar to the Eskimos and otherArctic tribes.",
        "KAYAKER": "One who uses a kayak.",
        "KAYKO": "The dog salmon.",
        "KAYLES": "A game; ninepins. [Prov Eng.] Carew.",
        "KAYNARD": "A lazy or cowardly person; a rascal. [Obs.] Chaucer.",
        "KAZOO": "A kind of toy or rude musical instrument, as a tube inside ofwhich is a stretched string made to vibrate by singing or humminginto the tube.",
        "KEA": "A large New Zealand parrot (Nestor notabilis), notorious forhaving acquired the habit of killing sheep; -- called also mountainparrot.",
        "KECK": "To heave or to retch, as in an effort to vomit. [R.] Swift.",
        "KECKLE": "See Keck, v. i. & n.",
        "KECKLING": "Old rope or iron chains wound around a cable. See Keckle, v. t.",
        "KECKLISH": "Inclined to vomit; squeamish. [R.] Holland.",
        "KECKSY": "The hollow stalk of an umbelliferous plant, such as the cowparsnip or the hemlock. [Written also kex, and in pl., kecks, kaxes.]Nothing teems But hateful docks, rough thistles, kecksies, burs.Shak.",
        "KECKY": "Resembling a kecksy. Grew.",
        "KEDDAH": "An inclosure constructed to entrap wild elephants; an elephanttrap. [India]",
        "KEDGE": "To move (a vessel) by carrying out a kedge in a boat, droppingit overboard, and hauling the vessel up to it.",
        "KEDGER": "A small anchor; a kedge.",
        "KEDLOCK": "See Charlock.",
        "KEE": "See Kie, Ky, and Kine. [Prov. Eng.] Gay.",
        "KEECH": "A mass or lump of fat rolled up by the butcher. [Obs.] Shak.",
        "KEEL": "To cool; to akin or stir [Obs.]While greasy Joan doth keel the pot. Shak.",
        "KEELAGE": "The right of demanding a duty or toll for a ship entering aport; also, the duty or toll. Bouvier. Wharton.",
        "KEELED": "Keel-shaped; having a longitudinal prominence on the back; as,a keeled leaf.",
        "KEELFAT": "A cooler; a vat for cooling wort, etc. [Written also keelvat.]Johnson.",
        "KEELHAUL": "To haul under the keel of a ship, by ropes attached to theyardarms on each side. It was formerly practiced as a punishment inthe Dutch and English navies. Totten.",
        "KEELING": "A cod.",
        "KEELIVINE": "A pencil of black or red lead; -- called also keelyvine pen.[Scot.] Sir W. Scott.",
        "KEELMAN": "See Keeler,",
        "KEELRAKE": "Same as Keelhaul.",
        "KEELS": "Ninepins. See Kayles.",
        "KEELSON": "A piece of timber in a ship laid on the middle of the floortimbers over the keel, and binding the floor timbers to the keel; iniron vessels, a structure of plates, situated like the keelson of atimber ship. Cross keelson, a similar structure lying athwart themain keelson, to support the engines and boilers.",
        "KEELVAT": "See Keelfat.",
        "KEEN": "To sharpen; to make cold. [R.]Cold winter keens the brightening flood. Thomson.",
        "KEENER": "A professional mourner who wails at a funeral. [Ireland]",
        "KEENLY": "In a keen manner.",
        "KEENNESS": "The quality or state of being keen.",
        "KEEP": "A cap for retaining anything, as a journal box, in place. Totake keep, to take care; to heed. [Obs.] Chaucer.",
        "KEEPERSHIP": "The office or position of a keeper. Carew.",
        "KEEPING": "Harmony or correspondence between the different parts of a workof art; as, the foreground of this painting is not in keeping.Keeping room, a family sitting room. [New Eng. & Prov. Eng.]",
        "KEEPSAKE": "Anything kept, or given to be kept, for the sake of the giver;a token of friendship.",
        "KEESH": "See Kish.",
        "KEEVE": "A vat or tub in which the mash is made; a mash tub. Ure.",
        "KEEVER": "See Keeve, n.",
        "KEFFE-KIL": "See Kiefekil.",
        "KEFIR": "An effervescent liquor like kumiss, made from fermented milk,used as a food and as a medicine in the northern Caucasus. --Ke*fir\"ic (#), a.",
        "KEFIR GRAINS": "Small hard yellowish aggregations found in the Caucasus region,and containing various yeasts and bacteria. They are used as aferment in preparing kefir.",
        "KEG": "A small cask or barrel.",
        "KEILHAUITE": "A mineral of a brownish black color, related to titanite inform. It consists chiefly of silica, titanium dioxide, lime, andyttria.",
        "KEIR": "See Kier.",
        "KEITLOA": "A black, two-horned, African rhinoceros (Atelodus keitloa). Ithas the posterior horn about as long as the anterior one, or evenlonger.",
        "KELD": "Having a kell or covering; webbed. [Obs.] Drayton.",
        "KELE": "To cool. [Obs.] Chaucer.",
        "KELL": "A kiln. [Obs.]",
        "KELOID": "Applied to a variety of tumor forming hard, flat, irregularexcrescences upon the skin.-- n.",
        "KELOTOMY": "See Celotomy.",
        "KELP": "Any large blackish seaweed.",
        "KELPFISH": "A small California food fish (Heterostichus rostratus), livingamong kelp. The name is also applied to species of the genusPlatyglossus.",
        "KELPWARE": "Same as Kelp, 2.",
        "KELSON": "See Keelson. Sir W. Raleigh.",
        "KELT": "See Kilt, n. Jamieson.",
        "KELTER": "Regular order or proper condition. [Written also kilter.][Colloq.]If the organs of prayer be out of kelter or out of tune, how can wepray Barrow.",
        "KELTIC": "Same as Celtic, a. & n.",
        "KEMB": "To comb. [Obs.]His longe hair was kembed behind his back. Chaucer.",
        "KEMELIN": "A tub; a brewer's vessel. [Obs.] Chaucer.",
        "KEMPE": "Rough; shaggy. [Obs.] \"Kempe hairs.\" Chaucer.",
        "KEMPS": "The long flower stems of the ribwort plantain (PlantagoLanceolata). Dr. Prior.",
        "KEMPT": "p. p. of Kemb. B. Jonson.",
        "KEN": "A house; esp., one which is a resort for thieves. [Slang, Eng.]",
        "KENNEL": "The water course of a street; a little canal or channel; agutter; also, a puddle. Bp. Hall.",
        "KENNEL COAL": ". See Cannel coal.",
        "KENO": "A gambling game, a variety of the game of lotto, played withballs or knobs, numbered, and cards also numbered. [U. S.]",
        "KENOGENESIS": "Modified evolution, in which nonprimitive characters make theirappearance in consequence of a secondary adaptation of the embryo tothe peculiar conditions of its environment; -- distinguished frompalingenesis. [Written also cænogenesis.]",
        "KENOGENETIC": "Of or pertaining to kenogenesis; as, kenogenetic processes.-- Ken`o*ge*net\"ic*al*ly, adv.",
        "KENSPECKLE": "Having so marked an appearance as easily to be recognized.[Scot.]",
        "KENT BUGLE": "A curved bugle, having six finger keys or stops, by means ofwhich the performer can play upon every key in the musical scale; --called also keyed bugle, and key bugle. Moore.",
        "KENTLE": "A hundred weight; a quintal.",
        "KENTLEDGE": "Pigs of iron used for ballast. [Written also kintlidge.]",
        "KENTUCKY": "One of the United States. Kentucky blue grass (Bot.), avaluable pasture and meadow grass (Poa pratensis), found in bothEurope and America. See under Blue grass.-- Kentucky coffee tree (Bot.), a tall North American tree(Gymnocladus Canadensis) with bipinnate leaves. It produces largewoody pods containing a few seeds which have been used as asubstitute for coffee. The timber is a very valuable.",
        "KEPHALIN": "One of a group of nitrogenous phosphorized principles, supposedby Thudichum to exist in brain tissue.",
        "KEPI": "A military cap having a close-fitting band, a round flat topsloping toward the front, and a visor. As originally worn by theFrench in Algeria about 1830 it was tall and stiff with a straightvisor. It is now lower, has a curved visor, and is frequently soft.",
        "KEPT": "of Keep. Kept mistress, a concubine; a woman supported by a manas his paramour.",
        "KEPVISELOHAZ": "See Legislature.",
        "KERAMIC": "Same as Ceramic.",
        "KERAMICS": "Same as Ceramics.",
        "KERAMOGRAPHIC": "Suitable to be written upon; capable of being written upon, asa slate; -- said especially of a certain kind of globe. Scudamore.",
        "KERANA": "A kind of long trumpet, used among the Persians. Moore (Encyc.of Music).",
        "KERARGYRITE": "See Cerargyrite.",
        "KERASIN": "A nitrogenous substance free from phosphorus, supposed to bepresent in the brain; a body closely related to cerebrin.",
        "KERASINE": "Resembling horn; horny; corneous.",
        "KERATIN": "A nitrogenous substance, or mixture of substances, containingsulphur in a loose state of combination, and forming the chemicalbasis of epidermal tissues, such as horn, hair, feathers, and thelike. It is an insoluble substance, and, unlike elastin, is notdissolved even by gastric or pancreatic juice. By decomposition withsulphuric acid it yields leucin and tyrosin, as does albumin. Calledalso epidermose.",
        "KERATITIS": "Inflammation of the cornea.",
        "KERATODE": "See Keratose.",
        "KERATOGENOUS": "Producing horn; as, the keratogenous membrane within the hornyhoof of the horse.",
        "KERATOIDEA": "Same as Keratosa.",
        "KERATOME": "An instrument for dividing the cornea in operations forcataract.",
        "KERATONYXIS": "The operation of removing a cataract by thrusting a needlethrough the cornea of the eye, and breaking up the opaque mass.",
        "KERATOPHYTE": "A gorgonian coral having a horny axis.",
        "KERATOSA": "An order of sponges having a skeleton composed of hornlikefibers. It includes the commercial sponges.",
        "KERATOSE": "A tough, horny animal substance entering into the compositionof the skeleton of sponges, and other invertebrates; -- called alsokeratode.",
        "KERAUNOGRAPH": "A figure or picture impressed by lightning upon the human bodyor elsewhere.-- Ker`au-nog\"ra-phy, n.",
        "KERB": "See Curb.",
        "KERBSTONE": "See Curbstone.",
        "KERCHER": "A kerchief. [Obs.]He became . . . white as a kercher. Sir T. North.",
        "KERCHERED": "Covered, or bound round, with a kercher. [Obs.] G. Fletcher.",
        "KERCHIEF": "Dressed; hooded; covered; wearing a kerchief. Milton.",
        "KERF": "A notch, channel, or slit made in any material by cutting orsawing.",
        "KERITE": "A compound in which tar or asphaltum combined with animal orvegetable oils is vulcanized by sulphur, the product closelyresembling rubber; -- used principally as an insulating material intelegraphy. Knight.",
        "KERL": "See Carl.",
        "KERMES": "The dried bodies of the females of a scale insect (Coccusilicis), allied to the cochineal insect, and found on several speciesof oak near the Mediterranean. They are round, about the size of apea, contain coloring matter analogous to carmine, and are used indyeing. They were anciently thought to be of a vegetable nature, andwere used in medicine. [Written also chermes.]",
        "KERMESSE": "See Kirmess.",
        "KERN": "An idler; a vagabond. Wharton.",
        "KERN BABY": "A doll or image decorated with corn (grain) flowers, etc.,carried in the festivals of a kern, or harvest-home. Called alsoharvest queen.",
        "KERNED": "Having part of the face projecting beyond the body or shank; --said of type. \"In Roman, f and j are the only kerned letters.\"MacKellar.",
        "KERNEL": "To harden or ripen into kernels; to produce kernels.",
        "KERNELLY": "Full of kernels; resembling kernels; of the nature of kernels.Holland.",
        "KERNISH": "Clownish; booorish. [Obs.] \"A petty kernish prince.\" Milton.",
        "KEROLITE": "Same as Cerolite.",
        "KEROSENE": "An oil used for illuminating purposes, formerly obtained fromthe distillation of mineral wax, bituminous shale, etc., and hencecalled also coal oil. It is now produced in immense quantities,chiefly by the distillation and purification of petroleum. Itconsists chiefly of several hydrocarbons of the methane series.",
        "KERSEY": "A kind of coarse, woolen cloth, usually ribbed, woven from woolof long staple.",
        "KERSEYMERE": "See Cassimere.",
        "KERSEYNETTE": "See Cassinette.",
        "KERSEYS": "Varieties of kersey; also, trousers made of kersey.",
        "KERVE": "To carve. [Obs.] Chaucer.",
        "KERVER": "A carver. [Obs.] Chaucer.",
        "KESAR": "See Kaiser [Obs.] Spenser.",
        "KESLOP": "The stomach of a calf, prepared for rennet. Halliwell.",
        "KESS": "To kiss. [Obs.] Chaucer",
        "KEST": "of Cast. [Obs.]",
        "KESTREL": "A small, slender European hawk (Falco alaudarius), allied tothe sparrow hawk. Its color is reddish fawn, streaked and spottedwith white and black. Also called windhover and stannel. The name isalso applied to other allied species.",
        "KET": "Carrion; any filth. [Prob. Eng.] Halliwell.",
        "KETA": "A small salmon (Oncorhynchus keta) of inferior value, which inthe autumn runs up all the larger rivers between San Francisco andKamchatka.",
        "KETCH": "An almost obsolete form of vessel, with a mainmast and amizzenmast, -- usually from one hundred to two hundred and fifty tonsburden. Bomb ketch. See under Bomb.",
        "KETCHUP": "A sauce. See Catchup.",
        "KETINE": "One of a series of organic bases obtained by the reduction ofcertain isonitroso compounds of the ketones. In general they areunstable oily substances having a pungent aromatic odor.",
        "KETMIE": "The name of certain African species of Hibiscus, cultivated forthe acid of their mucilage. [Written also ketmia.]",
        "KETOL": "One of a series of series of complex nitrogenous substances,represented by methyl ketol and related to indol. Methyl ketol, aweak organic base, obtained as a white crystalline substance havingthe odor of fæces.",
        "KETONE": "One of a large class of organic substances resembling thealdehydes, obtained by the distillation of certain salts of organicacids and consisting of carbonyl (CO) united with two hydrocarbonradicals. In general the ketones are colorless volatile liquidshaving a pungent ethereal odor.",
        "KETONIC": "Pertaining to, or derived from, a ketone; as, a ketonic acid.",
        "KETTLE": "A metallic vessel, with a wide mouth, often without a cover,used for heating and boiling water or other liguids. Kettle pins,ninepins; skittles. [Obs.] Shelton.-- Kettle stitch (Bookbinding), the stitch made in sewing at thehead and tail of a book. Knight.",
        "KETTLEDRUM": "A drum made of thin copper in the form of a hemisphericalkettle, with parchment stretched over the mouth of it.",
        "KETTLEDRUMMER": "One who plays on a kettledrum.",
        "KEUPER": "The upper division of the European Triassic. See Chart ofGeology.",
        "KEVEL": "A strong cleat to which large ropes are belayed.",
        "KEVER": "i. To cover. [Obs.] Chaucer.",
        "KEVERCHIEF": "A kerchief. [Obs.] Chaucer.",
        "KEX": "A weed; a kecksy. Bp. Gauden.Though the rough kex break The starred mosaic. Tennyson.",
        "KEY": "An indehiscent, one-seeded fruit furnished with a wing, as thefruit of the ash and maple; a samara; -- called also key fruit.",
        "KEY FRUIT": "A samara.",
        "KEY TONE": "See Keynote.",
        "KEY-COLD": "Cold as a metallic key; lifeless. [Formerly, a proverbialexpression.] Shak. Milton.",
        "KEYAGE": "Wharfage; quayage.",
        "KEYBOARD": "The whole arrangement, or one range, of the keys of an organ,typewriter, etc.",
        "KEYED": "Furnished with keys; as, a keyed instrument; also, set to akey, as a tune. Keyed bugle. See Kent bugle.",
        "KEYNOTE": "The tonic or first tone of the scale in which a piece orpassage is written; the fundamental tone of the chord, to which allthe modulations of the piece are referred; -- called also key tone.",
        "KEYSEAT": "To form a key seat, as by cutting. See Key seat, under Key.",
        "KEYSTONE": "The central or topmost stone of an arch. This in some styles ismade different in size from the other voussoirs, or projects, or isdecorated with carving. See Illust. of Arch. Keystone State, theState of Pennsylvania; -- so called from its having been the centralState of the Union at the formation of the Constitution.",
        "KEYSTONE STATE": "Pennsylvania; -- a nickname alluding to its having been thecentral one of the 13 original United States.",
        "KEYWAY": "See Key way, under Key.",
        "KHAKI": "Of a dull brownish yellow, or drab color; -- applied to cloth,originally to a stout brownish cotton cloth, used in making uniformsin the Anglo-Indian army. In the United States service the summeruniform of cotton is officially designated khaki; the winter uniformof wool, olive drab.",
        "KHALIFF": "See Caliph.",
        "KHAMSIN": "Same as Kamsin.",
        "KHAN": "A king; a prince; a chief; a governor; -- so called among theTartars, Turks, and Persians, and in countries now or formerlygoverned by them.",
        "KHANATE": "Dominion or jurisdiction of a khan.",
        "KHAYA": "A lofty West African tree (Khaya Senegalensis), related to themahogany, which it resembles in the quality of the wood. The bark isused as a febrifuge.",
        "KHEDIVE": "A governor or viceroy; -- a title granted in 1867 by the sultanof Turkey to the ruler of Egypt.",
        "KHENNA": "See Henna.",
        "KHOLAH": "The Indian jackal.",
        "KHOLSUN": "The dhole.",
        "KHOND": "A Dravidian of a group of tribes of Orissa, India, a section ofwhom were formerly noted for their cruel human sacrifices to theearth goddess, murder of female infants, and marriage by capture.",
        "KHUTBAH": "An address or public prayer read from the steps of the pulpitin Mohammedan mosques, offering glory to God, praising Mohammed andhis descendants, and the ruling princes.",
        "KIABOOCA WOOD": ". See Kyaboca wood.",
        "KIANG": "The dziggetai.",
        "KIBBLE": "To bruise; to grind coarsely; as, kibbled oats. [Prov.Eng.]Halliwell.",
        "KIBBLINGS": "Portions of small fish used for bait on the banks ofNewfoundland.",
        "KIBE": "A chap or crack in the flesh occasioned by cold; an ulceratedchilblain. \"He galls his kibe.\" Shak.",
        "KIBED": "Chapped; cracked with cold; affected with chilblains; as kibedheels. Beau. & Fl.",
        "KIBLAH": "See Keblah.",
        "KIBY": "Affected with kibes. Skelton.",
        "KICHIL": ",. [Obs.] See Kechil. Chaucer.",
        "KICK": "To strike, thrust, or hit violently with the foot; as, a horsekicks a groom; a man kicks a dog.He [Frederick the Great] kicked the shins of his judges. Macaulay.To kick the beam, to fit up and strike the beam; -- said of thelighter arm of a loaded balance; hence, to be found wanting inweight. Milton.-- To kick the bucket, to lose one's life; to die. [Colloq. & Low]",
        "KICKABLE": "Capable or deserving of being kicked. \"A kickable boy.\" G.Eliot.",
        "KICKAPOOS": "A tribe of Indians which formerly occupied the region ofNorthern Illinois, allied in language to the Sacs and Foxes.",
        "KICKER": "One who, or that which, kicks.",
        "KICKSHAW": "See Kickshaws, the correct singular.",
        "KICKSHOE": "A kickshaws. Milton.",
        "KICKSY-WICKSY": "Fantastic; restless; as, kicksy-wicksy flames. Nares.",
        "KICKUP": "The water thrush or accentor. [Local, West Indies]",
        "KID": "A young goat.The . . . leopard shall lie down with the kid. Is. xi. 6.",
        "KIDDE": "of Kythe. [Obs.] Chaucer.",
        "KIDDERMINSTER": "A kind of ingrain carpeting, named from the English town whereformerly most of it was manufactured.",
        "KIDDIER": "A huckster; a cadger. [Obs.] Halliwell.",
        "KIDDLE": "A kind of basketwork wear in a river, for catching fish.[Improperly spelled kittle.]",
        "KIDDOW": "The guillemot. [Written also kiddaw.] [Prov. Eng.]",
        "KIDDY": "To deceive; to outwit; to hoax. [Slang] Dickens.",
        "KIDDYISH": "Frolicsome; sportive. [Slang]",
        "KIDLING": "A young kid.",
        "KIDNAP": "To take (any one) by force or fear, and against one's will,with intent to carry to another place. Abbott.You may reason or expostulate with the parents, but never attempt tokidnap their children, and to make proselytes of them. Whately.",
        "KIDNEY": "A glandular organ which excretes urea and other waste productsfrom the animal body; a urinary gland.",
        "KIE": "Kine; cows. [Prov. Eng.] Halliwell.",
        "KIEFEKIL": "A species of clay; meerschaum. [Also written keffekil.]",
        "KIER": "A large tub or vat in which goods are subjected to the actionof hot lye or bleaching liquor; -- also called keeve.",
        "KIESELGUHR": "Siliceous earth; specifically, porous infusorial earth, used asan absorbent of nitroglycerin in the manufacture of dynamite.",
        "KIESERITE": "Hydrous sulphate of magnesia found at the salt mines ofStassfurt, Prussian Saxony.",
        "KIEVE": "See Keeve, n.",
        "KIKE": "To gaze; to stare. [Obs.] Chaucer.",
        "KILDERKIN": "A small barrel; an old liquid measure containing eighteenEnglish beer gallons, or nearly twenty-two gallons, United Statesmeasure. [Written also kinderkin.]",
        "KILERG": "A unit of work equal to one thousand ergs.",
        "KILKENNY CATS": "Two cats fabled, in an Irish story, to have fought till nothingwas left but their tails. It is probably a parable of a local contestbetween Kilkenny and Irishtown, which impoverished both towns.",
        "KILL": "A kiln. [Obs.] Fuller.",
        "KILL-JOY": "One who causes gloom or grief; a dispiriting person. W. Black.",
        "KILLER": "A voracious, toothed whale of the genus Orca, of which severalspecies are known.",
        "KILLIFISH": "Any one of several small American cyprinodont fishes of thegenus Fundulus and allied genera. They live equally well in fresh andbrackish water, or even in the sea. They are usually striped orbarred with black. Called also minnow, and brook fish. See Minnow.",
        "KILLIGREW": "The Cornish chough. See under Chough. [Prov. Eng. & Scot.]",
        "KILLIKINICK": "See Kinnikinic.",
        "KILLING": "Literally, that kills; having power to kill; fatal; in acolloquial sense, conquering; captivating; irresistible.-- Kill\"ing*ly, adv.Those eyes are made so killing. Pope.Nothing could be more killingly spoken. Milton.",
        "KILLOCK": "A small anchor; also, a kind of anchor formed by a stoneinclosed by pieces of wood fastened together. [Written also killick.]",
        "KILLOW": "An earth of a blackish or deep blue color. Woodward.",
        "KILN-DRY": "To dry in a kiln; as, to kiln-dry meal or grain. Mortimer.",
        "KILNHOLE": "The mouth or opening of an oven or kiln. Shak.",
        "KILO": "An abbreviation of Kilogram.",
        "KILO-": "A combining form used to signify thousand in forming the namesof units of measurement; as, kilogram, kilometer, kilowatt, etc.",
        "KILOSTERE": "A cubic measure containing 1000 cubic meters, and equivalent to35,315 cubic feet.",
        "KILOVOLT": "A unit of electromotive force equal to one thousand volts.",
        "KILOWATT": "One thousand watts.",
        "KILOWATT HOUR": "A unit of work or energy equal to that done by one kilowattacting for one hour; --approx. = 1.34 horse-power hour.",
        "KILT": "p. p. from Kill. [Obs.] Spenser.",
        "KILTER": "See Kelter.",
        "KILTING": "A perpendicular arrangement of flat, single plaits, each plaitbeing folded so as to cover half the breadth of the preceding one.",
        "KIMBO": "Crooked; arched; bent. [Written also kimbow.] Dryden.",
        "KIMMERIAN": "See Cimmerian.",
        "KIMNEL": "A tub. See Kemelin. [Obs.]She knew not what a kimnel was Beau. & Fl.",
        "KIMRY": "See Cymry.",
        "KIN": "A diminutive suffix; as, manikin; lambkin.",
        "KINAESODIC": "Kinesodic.",
        "KINAESTHESIS": "The perception attendant upon the movements of the muscles.Bastian.",
        "KINATE": "See Quinate. [Obsolescent]",
        "KINCOB": "India silk brocaded with flowers in silver or gold.-- a.",
        "KIND": "To beget. [Obs.] Spenser.",
        "KIND-HEARTED": "Having kindness of nature; sympathetic; characterized by ahumane disposition; as, a kind-hearted landlord.To thy self at least kind-hearted prove. Shak.",
        "KIND-HEARTEDNESS": "The state or quality of being kind-hearted; benevolence.",
        "KINDERGARTEN": "A school for young children, conducted on the theory thateducation should be begun by gratifying and cultivating the normalaptitude for exercise, play, observation, imitation, andconstruction; -- a name given by Friedrich Froebel, a Germaneducator, who introduced this method of training, in rooms opening ona garden.",
        "KINDERGARTNER": "One who teaches in a kindergarten.",
        "KINDLE": "To bring forth young. [Obs.] Shak.The poor beast had but lately kindled. Holland.",
        "KINDLER": "One who, or that which, kindles, stirs up, or sets onfire.\"Kindlers of riot.\" Gay.",
        "KINDLESS": "Destitute of kindness; unnatural.[Obs.] \"Kindless villain.\"Shak.",
        "KINDLING": "Materials, easily lighted, for starting a fire.",
        "KINDRED": "Related; congenial; of the like nature or properties; as,kindred souls; kindred skies; kindred propositions.True to the kindred points of heaven and home. Wordsworth.",
        "KINE": "Cows. \"A herd of fifty or sixty kine.\" Milton.",
        "KINEMATICS": "The science which treats of motions considered in themselves,or apart from their causes; the comparison and relation of motions.",
        "KINEPOX": "See Cowpox. Kin\"e*scope (, n.",
        "KINESIATRICS": "A mode of treating disease by appropriate muscular movements; -- also termed kinesitherapy, kinesipathy, lingism, and the movementcure.",
        "KINESIPATHY": "See Kinesiatrics.",
        "KINESITHERAPY": "See Kinesiatrics.",
        "KINESODIC": "Conveying motion; as; kinesodic substance; -- applied esp. tothe spinal cord, because it is capable of conveying doth voluntaryand reflex motor impulses, without itself being affected by motorimpulses applied to it directly.",
        "KINETIC": "Moving or causing motion; motory; active, as opposed to latent.Kinetic energy. See Energy, n. 4.",
        "KINETICS": "See Dynamics.",
        "KINETOGENESIS": "An instrument for producing curves by the combination ofcircular movements; -- called also kinescope.",
        "KINETOPHONE": "A machine combining a kinetoscope and a phonograph synchronizedso as to reproduce a scene and its accompanying sounds.",
        "KINETOSCOPE": "A machine, for the production of animated pictures, in which afilm carrying successive instantaneous views of a moving scenetravels uniformly through the field of a magnifying glass. Theobserver sees each picture, momentarily, through a slit in arevolving disk, and these glimpses, blended by persistence of vision,give the impression of continuous motion.",
        "KING": "A Chinese musical instrument, consisting of resonant stones ormetal plates, arranged according to their tones in a frame of wood,and struck with a hammer.",
        "KING CHARLES SPANIEL": "A variety of small pet dogs, having, drooping ears, a high,dome-shaped forehead, pug nose, large, prominent eyes, and long, wavyhair. The color is usually black and tan.",
        "KING-POST": "A member of a common form of truss, as a roof truss. It isstrictly a tie, intended to prevent the sagging of the tiebeam in themiddle. If there are struts, supporting the main rafters, they oftenbear upon the foot of the king-post. Called also crown-post.",
        "KINGBOLT": "A vertical iron bolt, by which the forward axle and wheels of avehicle or the trucks of a railroad car are connected with the otherparts.",
        "KINGCRAFT": "The craft of kings; the art of governing as a sovereign; royalpolicy. Prescott.",
        "KINGCUP": "The common buttercup.",
        "KINGDOMED": "Having a kingdom or the dignity of a king; like a kingdom. [R.]\"Twixt his mental and his active parts, Kingdom'd Achilles incommotion rages And batters down himself. Shak.",
        "KINGFISHER": "Any one of numerous species of birds constituting the familyAlcedinidæ. Most of them feed upon fishes which they capture bydiving and seizing then with the beak; others feed only uponreptiles, insects, etc. About one hundred and fifty species areknown. They are found in nearly all parts of the world, but areparticularly abundant in the East Indies.",
        "KINGHOOD": "The state of being a king; the attributes of a king; kingship.Gower.",
        "KINGLESS": "Having no king. F. Lieber.",
        "KINGLET": "Any one of several species of small singing birds of the genusRegulus and family Sylviidæ.",
        "KINGLIHOOD": "King-liness. Tennyson.",
        "KINGLINESS": "The state or quality of being kingly.",
        "KINGLING": "Same as Kinglet, 1. Churchill.",
        "KINGLY": "Belonging to, suitable to, or becoming, a king; characteristicof, resembling, a king; directed or administered by a king;monarchical; royal; sovereign; regal; august; noble; grand. \"Kinglymagnificence.\" Sir P. Sidney. \"A kingly government.\" Swift. \"Thekingly couch.\" Shak.The kingliest kings are crowned with thorn. G. Massey.Leave kingly backs to cope with kingly cares. Cowper.",
        "KINGSHIP": "The state, office, or dignity of a king; royalty. Landor.",
        "KINGSTON METAL": ". An alloy of tin, copper, and mercury, sometimes used for thebearings and packings of machinery. McElrath.",
        "KINGSTON VALVE": "A conical valve, opening outward, to close the mouth of a pipewhich passes through the side of a vessel below the water line.",
        "KINGTRUSS": "A truss, framed with a king-post; -- used in roofs, bridges,etc.",
        "KINIC": "See Quinic.",
        "KINIT": "A unit of force equal to the force which, acting for onesecond, will give a pound a velocity of one foot per second; --proposed by J.D.Everett, an English physicist.",
        "KINK": "To wind into a kink; to knot or twist spontaneously uponitself, as a rope or thread.",
        "KINKAJOU": "A nocturnal carnivorous mammal (Cercoleptes caudivolvulus) ofSouth America, about as large as a full-grown cat. It has aprehensile tail and lives in trees. It is the only representative ofa distinct family (Cercoleptidæ) allied to the raccoons. Called alsopotto, and honey bear.",
        "KINKHAUST": "Whooping cough. [Obs.or Prov. Eng.]",
        "KINKLE": "Same as 3d Kink.",
        "KINNIKINIC": "Prepared leaves or bark of certain plants; -- used by theIndians of the Northwest for smoking, either mixed with tobacco or asa substitute for it. Also, a plant so used, as the osier cornel(Cornus stolonijra), and the bearberry (Arctostaphylus Uva-ursi).[Spelled also kinnickinnick and killikinick.]",
        "KINO": "The dark red dried juice of certain plants, used variously intanning, in dyeing, and as an astringent in medicine.",
        "KINOLOGY": "That branch of physics which treats of the laws of motion, orof moving bodies.",
        "KINONE": "See Quinone.",
        "KINOYL": "See Quinoyl.",
        "KINREDE": "Kindred. [Obs.] Chaucer.",
        "KINSFOLK": "Relatives; kindred; kin; persons of the same family or closelyor closely related families.They sought him among their kinsfolk and acquaintance. Luke ii. 44.",
        "KINSHIP": "Family relationship.",
        "KINSMAN": "A man of the same race or family; one related by blood.",
        "KINSMANSHIP": "Kinship. Thackeray.",
        "KINSWOMAN": "A female relative. Shak.",
        "KINTLIDGE": "See Kentledge.",
        "KIOSK": "A Turkish open summer house or pavilion, supported by pillars.",
        "KIOWAYS": "A tribe of Indians distantly related to the Shoshones. Theyformerly inhabited the region about the head waters of the NorthPlatte.",
        "KIP": "The hide of a young or small beef creature, or leather madefrom it; kipskin. Kip leather. See Kipskin.",
        "KIPE": "An osier basket used for catching fish. [Prov. Eng.]",
        "KIPPER": "A salmon after spawning.",
        "KIPPERNUT": "A name given to earthnuts of several kinds.",
        "KIPSKIN": "Leather prepared from the skin of young or small cattle,intermediate in grade between calfskin and cowhide.",
        "KIRK": "A church or the church, in the various senses of the word;esp., the Church of Scotland as distinguished from other reformedchurches, or from the Roman Catholic Church. [Scot.] Jamieson.",
        "KIRKED": "Turned upward; bent. [Obs.] Rom. of R.",
        "KIRKYARD": "A churchyard. [Scot.]",
        "KIRMESS": "In Europe, particularly in Belgium and Holland, and outdoorfestival and fair; in the United States, generally an indoorentertainment and fair combined.",
        "KIRSCHWASSER": "An alcoholic liquor, obtained by distilling the fermented juiceof the small black cherry.",
        "KIRSOME": "Christian; christened. [Obs.]I am a true kirsome woman. Beau. & Fl.",
        "KIRTLE": "A garment varying in form and use at different times, and worndoth by men and women.Wearing her Norman car, and her kirtle of blue. Longfellow.",
        "KIRTLED": "Wearing a kirtle. Byron.",
        "KIRUMBO": "A bird of Madagascar (Leptosomus discolor), the only livingtype of a family allied to the rollers. It has a pair of loralplumes. The male is glossy green above, with metallic reflections;the female is spotted with brown and black.",
        "KISH": "A workman's name for the graphite which forms incidentally iniron smelting.",
        "KISMET": "Destiny; fate. [Written also kismat.] [Oriental]",
        "KISSER": "One who kisses. Beau. & Fl.",
        "KISSING BUG": "Any one of several species of blood-sucking, venomous Hemipterathat sometimes bite the lip or other parts of the human body, causingpainful sores, as the cone-nose (Conorhinus sanguisuga). [U. S.]",
        "KISSING STRINGS": "Cap or bonnet strings made long to tie under the chin.",
        "KISSINGCRUST": "The portion of the upper crust of a loaf which has touchedanother loaf in baking. Lamb.A massy fragment from the rich kissingcrust that hangs like a frettedcornice from the upper half of the loaf. W. Howitt.",
        "KIST": "A chest; hence, a coffin. [Scot. & Prov. End.] Jamieson.Halliwell.",
        "KISTVAEN": "A Celtic monument, commonly known as a dolmen.",
        "KIT": "To cut. [Obs.] Chaucer.",
        "KITCAT": "A game played by striking with a stick small piece of wood,called a cat, shaped like two coned united at their bases; tipcat.Cotton. Kitcat roll (Agric.), a roller somewhat in the form of twocones set base to base. [Prov. Eng.]",
        "KITCHEN": "To furnish food to; to entertain with the fare of the kitchen.[Obs.] Shak.",
        "KITCHEN MIDDENS": "Relics of neolithic man found on the coast of Denmark,consisting of shell mounds, some of which are ten feet high, onethousand feet long, and two hundred feet wide. The name is appliedalso to similar mounds found on the American coast from Canada toFlorida, made by the North American Indians.",
        "KITCHEN-RY": "The body of servants employed in the kitchen. [Obs.] Holland.",
        "KITCHENER": "A kitchen servant; a cook. Carlyle.",
        "KITCHENETTE": "A room combining a very small kitchen and a pantry, with thekitchen conveniences compactly arranged, sometimes so that they foldup out of sight and allow the kitchen to be made a part of theadjoining room by opening folding doors.",
        "KITCHENMAID": "A woman employed in the kitchen. Shak.",
        "KITE": "Any raptorial bird of the subfamily Milvinæ, of which manyspecies are known. They have long wings, adapted for soaring, andusually a forked tail.",
        "KITH": "Acquaintance; kindred.And my near kith for sore me shend. W. Browne.The sage of his kith and the hamlet. Longfellow.Kith and kin, kindred more or less remote.",
        "KITHARA": "See Cithara.",
        "KITHE": "See Kythe. Chaucer.",
        "KITISH": "Like or relating to a kite.",
        "KITLING": "A young kitten; a whelp. [Obs. or Scot.] B. Jonson.",
        "KITTE": "of Kit to cut. [Obs.] Chaucer.",
        "KITTEL": "See Kittle, v. t.",
        "KITTEN": "A young cat.",
        "KITTENISH": "Resembling a kitten; playful; as, a kittenish disposition.Richardson.",
        "KITTIWAKE": "A northern gull (Rissa tridactyla), inhabiting the coasts ofEurope and America. It is white, with black tips to the wings, andhas but three toes.",
        "KITTLE": "To bring forth young, as a cat; to kitten; to litter. [Prov.Eng. & Scot.]",
        "KITTLISH": "Ticklish; kittle. Sir W. Scott.",
        "KITTYSOL": "The Chinese paper parasol.",
        "KIVA": "A large chamber built under, or in, the houses of a Pueblovillage, used as an assembly room in religious rites or as a men'sdormitory. It is commonly lighted and entered from an opening in theroof.",
        "KIVE": "A mash vat. See Keeve. [Obs.]",
        "KIVER": "To cover.-- n.",
        "KJOEKKEN MOEDDINGS": "See Kitchen middens.",
        "KLAMATHS": "A collective name for the Indians of several tribes formerlyliving along the Klamath river, in California and Oregon, but nowrestricted to a reservation at Klamath Lake; -- called also Clametsand Hamati.",
        "KLEENEBOC": "(Zoöl.) An antelope (Cerphalopus pygmæus), found in SouthAfrica. It is of very small size, being but one foot high atshoulder. It is remarkable for its activity, and for its mild andtimid disposition. Called also guevi, and pygmy antelope.",
        "KLEPTOMANIA": "A propensity to steal, claimed to be irresistible. This doesnot constitute legal irresponsibility. Wharton.",
        "KLEPTOMANIAC": "A person affected with kleptomania.",
        "KLICK": "See Click.",
        "KLICKET": "A small postern or gate in a palisade, for the passage ofsallying parties. [Written also klinket.]",
        "KLINKSTONE": "See Clinkstone.",
        "KLINOMETER": "See Clinometer.",
        "KLIPFISH": "Dried cod, exported from Norway. [Written also clipfish.]",
        "KLIPSPRINGER": "A small, graceful South African antelope (Nanotragusoreotragus), which, like the chamois, springs from one crag toanother with great agility; -- called also kainsi. [Written alsoklippspringer.]",
        "KLOOF": "A glen; a ravine closed at its upper end. [South Africa]",
        "KLOPEMANIA": "See Kleptomania.",
        "KNABBLE": "To bite or nibble. [Obs.]Horses will knabble at walls, and rats gnaw iron. Sir T. Browne.",
        "KNACK-KNEED": "See Knock-kneed.",
        "KNACKISH": "Trickish; artful. [Obs.] -- Knack\"ish*ness, n. [Obs.] Dr. H.More.",
        "KNACKY": "Having a knack; cunning; crafty; trickish. [Prov. Eng. & Scot.]Halliwell.",
        "KNAGGED": "Full of knots; knaggy.",
        "KNAGGY": "Knotty; rough; figuratively, rough in temper. Fuller.-- Knag\"gi*ness, n.",
        "KNAP": "A protuberance; a swelling; a knob; a button; hence, risingground; a summit. See Knob, and Knop.The highest part and knap of the same island. Holland.",
        "KNAPBOTTLE": "The bladder campion (Silene inflata).",
        "KNAPPISH": "Snappish; peevish. [Obs.] Grafton.",
        "KNAPPLE": "To break off with an abrupt, sharp noise; to bite; to nibble.[Obs. or Prov. Eng.]",
        "KNAPPY": "Having knaps; full of protuberances or humps; knobby. [Obs.]Huloet.",
        "KNAPSACK": "A case of canvas or leather, for carrying on the back asoldier's necessaries, or the clothing, etc., of a traveler.And each one fills his knapsack or his scrip With some rare thingthat on the field is found. Drayton.",
        "KNAPWEED": "The black centaury (Centaurea nigra); -- so called from theknoblike heads of flowers. Called also bullweed.",
        "KNAR": "See Gnar. [Obs.] Chaucer.",
        "KNARL": "A knot in wood. See Gnarl.",
        "KNARLED": "Knotted. See Gnarled.",
        "KNARRED": "Knotty; gnarled.The knarred and crooked cedar knees. Longfellow.",
        "KNARRY": "Knotty; gnarled. Chaucer.",
        "KNAVERY": "Roguish or mischievous tricks. Shak.",
        "KNAVESHIP": "A small due, in meal, established by usage, which is paid tothe under miller. [Scot.]",
        "KNAVESS": "A knavish woman. Carlyle.",
        "KNAVISHNESS": "The quality or state of being knavish; knavery; dishonesty.",
        "KNAW": "See Gnaw. [Obs.] Sir T. More.",
        "KNAWEL": "A low, spreading weed (Scleranthus annuus), common in sandysoil.",
        "KNEADABLE": "That may be kneaded; capable of being worked into a mass.",
        "KNEADER": "One who kneads.",
        "KNEADINGLY": "In the manner of one kneading.",
        "KNEBELITE": "A mineral of a gray, red, brown, or green color, and glisteningluster. It is a silicate of iron and manganese.",
        "KNECK": "The twisting of a rope or cable, as it is running out. [Eng.]",
        "KNEE": "A piece of timber or metal formed with an angle somewhat in theshape of the human knee when bent.",
        "KNEE JERK": "A jerk or kick produced by a blow or sudden strain upon thepatellar tendon of the knee, which causes a sudden contraction of thequadriceps muscle.",
        "KNEE-CROOKING": "Obsequious; fawning; cringing. \"Knee-crooking knave.\" Shak.",
        "KNEE-HIGH": "Rising or reaching upward to the knees; as, the water is knee-high.",
        "KNEEBRUSH": "A tuft or brush of hair on the knees of some species ofantelopes and other animals; -- chiefly used in the plural.",
        "KNEECAP": "The kneepan.",
        "KNEED": "Geniculated; forming an obtuse angle at the joints, like theknee when a little bent; as, kneed grass.",
        "KNEEJOINT": "A toggle joint; -- so called because consisting of two piecesjointed to each other end to end, making an angle like the knee whenbent.",
        "KNEEJOINTED": "Geniculate; kneed. See Kneed, a., 2.",
        "KNEEL": "To bend the knee; to fall or rest on the knees; -- sometimeswith down.And he kneeled down, and cried with a loud voice, Lord, lay not thissin to their charge. Acts vii. 60.As soon as you are dressed, kneel and say the Lord's Prayer. Jer.Taylor.",
        "KNEELER": "A name given to certain catechumens and penitents who werepermitted to join only in parts of church worship.",
        "KNEELINGLY": "In a kneeling position.",
        "KNEEPAN": "A roundish, flattened, sesamoid bone in the tendon in front ofthe knee joint; the patella; the kneecap.",
        "KNEEPIECE": "A piece shaped like a knee; as, the kneepieces or ears of aboat.",
        "KNELL": "The stoke of a bell tolled at a funeral or at the death of aperson; a death signal; a passing bell; hence, figuratively, awarning of, or a sound indicating, the passing away of anything.The dead man's knell Is there scarce asked for who. Shak.The curfew tolls the knell of parting day. Gray.",
        "KNELT": "of Kneel.",
        "KNEW": "of Know.",
        "KNICKER": "A small ball of clay, baked hard and oiled, used as a marble byboys in playing. [Prov. Eng. & U. S.] Halliwell. Bartlett.",
        "KNICKERBOCKER": "A linsey-woolsey fabric having a rough knotted surface on theright side; used for women's dresses.",
        "KNICKERBOCKERS": "The name for a style of short breeches; smallclothes.",
        "KNICKKNACK": "A trifle or toy; a bawble; a gewgaw.",
        "KNICKKNACKATORY": "A collection of knickknacks. Richardson.",
        "KNICKKNACKERY": "Knickknacks.",
        "KNIFE": "To prune with the knife.",
        "KNIFE SWITCH": "A switch consisting of one or more knifelike pieces hinged atone end and making contact near the other with flat gripping springs.",
        "KNIFEBOARD": "A board on which knives are cleaned or polished.",
        "KNIGHT": "To dub or create (one) a knight; -- done in England by thesovereign only, who taps the kneeling candidate with a sword, saying:Rise, Sir ---.A soldier, by the honor-giving hand Of Cknighted in the field. Shak.",
        "KNIGHT BACHELOR": "A knight of the most ancient, but lowest, order of Englishknights, and not a member of any order of chivalry. See Bachelor, 4.",
        "KNIGHT BANNERET": "A knight who carried a banner, who possessed fiefs to a greateramount than the knight bachelor, and who was obliged to serve in warwith a greater number of attendants. The dignity was sometimesconferred by the sovereign in person on the field of battle.",
        "KNIGHT BARONET": "See Baronet.",
        "KNIGHT MARSHAL": "An officer in the household of the British sovereign, who hascognizance of transgressions within the royal household and verge,and of contracts made there, a member of the household being one ofthe parties. Wharton.",
        "KNIGHT SERVICE": "A tenure of lands held by knights on condition of performingmilitary service. See Chivalry, n., 4.",
        "KNIGHT TEMPLAR": "See Commandery, n., 3, and also Templar, n., 1 and 3.",
        "KNIGHT-ER-RATIC": "Pertaining to a knight-errant or to knight-errantry. [R.]Quart. Rev.",
        "KNIGHT-ERRANT": "A wandering knight; a knight who traveled in search ofadventures, for the purpose of exhibiting military skill, prowess,and generosity.",
        "KNIGHT-ERRANTRY": "The character or actions of wandering knights; the practice ofwandering in quest of adventures; chivalry; a quixotic or romanticadventure or scheme.The rigid guardian [i. e., conscience] of a blameless heart Is weakwith rank knight-erratries o'errun. Young.",
        "KNIGHTAGE": "To body of knights, taken collectively.",
        "KNIGHTHEAD": "A bollard timber. See under Bollard.",
        "KNIGHTLESS": "Unbecoming a knight. [Obs.] \"Knightless guile.\" Spenser.",
        "KNIGHTLINESS": "The character or bearing suitable for a knight; chivalry.Spenser.",
        "KNIGHTLY": "Of or pertaining to a knight; becoming a knight; chivalrous;as, a knightly combat; a knightly spirit.For knightly jousts and fierce encounters fit. Spenser.[Excuses] full knightly without scorn. Tennyson.",
        "KNIT": "Union knitting; texture. Shak.",
        "KNITBACK": "The plant comfrey; -- so called from its use as a restorative.Dr. Prier.",
        "KNITS": "Small particles of ore. Raymond.",
        "KNITSTER": "A woman who knits. [Prov. Eng.] Halliwell.",
        "KNITTER": "One who, or that which, knits, joins, or unites; a knittingmachine. Shak.",
        "KNITTLE": "See Nettles.",
        "KNIVES": "of Knife. See Knife.",
        "KNOB": "See Knop. Knob latch, a latch which can be operated by turninga knob, without using a key.",
        "KNOBBED": "Containing knobs; full of knobs; ending in a nob. See Illust ofAntenna.The horns of a roe deer of Greenland are pointed at the top, andknobbed or tuberous at the bottom. Grew.",
        "KNOBBER": "See Knobbler.",
        "KNOBBING": "Rough dressing by knocking off knobs or projections.",
        "KNOBBLER": "The hart in its second year; a young deer. [Written alsoknobber.] Halliwell.He has hallooed the hounds upon a velvet-headed knobbler. Sir W.Scott.",
        "KNOBBLING FIRE": ". A bloomery fire. See Bloomery.",
        "KNOBKERRIE": "A short club with a knobbed end used as a missile weapon byKafir and other native tribes of South Africa.",
        "KNOBSTICK": "One who refuses to join, or withdraws from, a trades union.[Cant, Eng.]",
        "KNOCK-KNEE": "A condition in which the knees are bent in so as to touch eachother in walking; inknee.",
        "KNOCK-KNEED": "Having the legs bent inward so that the knees touch in walking.[Written also knack-kneed.]",
        "KNOCK-OFF": "That knocks off; of or pertaining to knocking off.",
        "KNOCK-OUT": "Act of knocking out, or state of being knocked out.",
        "KNOCK-OUT DROPS": "Drops of some drug put in one's drink to stupefy him forpurpose of robbery, etc. [Slang, U. S.]",
        "KNOCKDOWN": "A felling by a knock, as of a combatant, or of an animal.",
        "KNOCKER": "One who, or that which, knocks; specifically, an instrument, orkind of hammer, fastened to a door, to be used in seeking foradmittance.Shut, shut the door, good John ! fatigued, knocker; say I'm sick, I'mdead. Pope.",
        "KNOCKING": "A beating; a rap; a series of raps.The . . . repeated knockings of the head upon the ground by theChinese worshiper. H. Spencer.",
        "KNOCKINGS": "Large lumps picked out of the sieve, in dressing ore.",
        "KNOCKSTONE": "A block upon which ore is broken up.",
        "KNOLL": "A little round hill; a mound; a small elevation of earth; thetop or crown of a hill.On knoll or hillock rears his crest, Lonely and huge, the giant oak.Sir W. Scott.",
        "KNOLLER": "One who tolls a bell. [Obs.] Sherwood.",
        "KNOP": "Any boldly projecting sculptured ornament; esp., the ornamentaltermination of a pinnacle, and then synonymous with finial; -- calledalso knob, and knosp. Knop sedge (Bot.), the bur reed (Sparganium); -- so called from its globular clusters of seed vessels. Prior.",
        "KNOPPED": "Having knops or knobs; fastened as with buttons. [Obs.] Rom. ofR.",
        "KNOPPERN": "A kind of gall produced by a gallfly on the cup of an acorn, --used in tanning and dyeing.",
        "KNOPWEED": "Same as Knapweed.",
        "KNOR": "See Knur. [Obs.]",
        "KNOSP": "Same as Knop,2. Milman.",
        "KNOT": "See Node.",
        "KNOTBERRY": "The cloudberry (Rudus Chamæmorus); -- so called from itsknotted stems.",
        "KNOTLESS": "Free from knots; without knots. \"Silver firs with knotlesstrunks.\" Congreve.",
        "KNOTTED": "Characterized by small, detached points, chiefly composed ofmica, less decomposable than the mass of the rock, and forming knotsin relief on the weathered surface; as, knotted rocks. Percival.",
        "KNOTWEED": "See Knot.",
        "KNOTWORT": "A small, herbaceous, trailing plant, of the genus Illecebrum(I. verticillatum.)",
        "KNOUT": "A kind of whip for flogging criminals, formerly much used inRussia. The last is a tapering bundle of leather thongs twisted withwire and hardened, so that it mangles the flesh.",
        "KNOW": "Knee. [Obs.] Chaucer.",
        "KNOW-ALL": "One who knows everything; hence, one who makes pretension togreat knowledge; a wiseacre; -- usually ironical. [Colloq. or R.]",
        "KNOW-NOTHING": "A member of a secret political organization in the UnitedStates, the chief objects of which were the proscription offoreigners by the repeal of the naturalization laws, and theexclusive choice of native Americans for office.",
        "KNOW-NOTHINGISM": "The doctrines, principles, or practices, of the Know-nothings.",
        "KNOWABLE": "That may be known; capable of being discovered, understood, orascertained.Thus mind and matter, as known or knowable, are only two differentseries of phenomena or qualities. Sir W. Hamilton.",
        "KNOWABLENESS": "The state or quality of being knowable. Locke.",
        "KNOWER": "One who knows. Shak.",
        "KNOWING": "Knowledge; hence, experience. \" In my knowing.\" Shak.This sore night Hath trifled former knowings. Shak.",
        "KNOWINGNESS": "The state or quality of being knowing or intelligent;shrewdness; skillfulness.",
        "KNOWLECHE": "See Knowl, edge.We consider and knowleche that we have offended. Chaucer.",
        "KNOWLECHING": "Knowledge. [Obs.] Chaucer.",
        "KNOWLEDGE": "To acknowledge. [Obs.] \"Sinners which knowledge their sins.\"Tyndale.",
        "KNOWN": "of Know.",
        "KNUBS": "Waste silk formed in winding off the threads from a cocoon.",
        "KNUCKLE": "The joining pars of a hinge through which the pin or rivetpasses; a knuckle joint.",
        "KNUCKLED": "Jointed. [Obs.] Bacon.",
        "KNUFF": "A lout; a clown. [Obs.]The country knuffs, Hob, Dick, and Hick, With clubs and cloutedshoon. Hayward.",
        "KNUR": "A knurl. Woodward.",
        "KNURL": "A contorted knot in wood; a crossgrained protuberance; anodule; a boss or projection.",
        "KNURLY": "Full of knots; hard; tough; hence, capable of enduring orresisting much.",
        "KNURRY": "Full of knots. [Obs.] Drayton.",
        "KOAITA": "Same as Coaita.",
        "KOALA": "A tailless marsupial (Phascolarctos cinereus), found inAustralia. The female carries her young on the back of her neck.Called also Australian bear, native bear, and native sloth.",
        "KOBALT": "See Cobalt.",
        "KOBELLITE": "A blackish gray mineral, a sulphide of antimony, bismuth, andlead.",
        "KOBOLD": "A kind of domestic spirit in German mythology, corresponding tothe Scottish brownie and the English Robin Goodfellow.",
        "KODAK": "A kind of portable camera.",
        "KOEL": "Any one of several species of cuckoos of the genus Eudynamys,found in India, the East Indies, and Australia. They deposit theireggs in the nests of other birds.",
        "KOFF": "A two-masted Dutch vessel.",
        "KOFTGARI": "Ornamental work produced by inlaying steel with gold, -- avariety of damascening much used in the arts of India.",
        "KOHL": "A mixture of soot and other ingredients, used by Egyptian andother Eastern women to darken the edges of the eyelids.",
        "KOHL-RABI": "A variety of cabbage, in which the edible part is a large,turnip-shaped swelling of the stem, above the surface of the ground.",
        "KOKAMA": "The gemsbok.",
        "KOKLASS": "Any pheasant of the genus Pucrasia. The birds of this genusinhabit India and China, and are distinguished by having a longcentral and two lateral crests on the head. Called also pucras.",
        "KOKOON": "The gnu.",
        "KOLARIAN": "An individual of one of the races of aboriginal inhabitantswhich survive in Hindostan.-- a.",
        "KOLINSKY": "Among furriers, any of several Asiatic minks; esp., Putoriussibiricus, the yellowish brown pelt of which is valued, esp. for thetail, used for making artists' brushes. Trade names for the fur arered sable and Tatar sable.",
        "KOMENIC": "Of or pertaining to, or designating, an acid derived frommeconic acid. [Written also comenic.]",
        "KOMTOK": "An African freshwater fish (Protopterus annectens), belongingto the Dipnoi. It can breathe air by means of its lungs, and whenwaters dry up, it encases itself in a nest of hard mud, where itremains till the rainy season. It is used as food.",
        "KON": "To know. See Can, and Con. [Obs.]Ye konnen thereon as much as any man. Chaucer.",
        "KONITE": "See Conite.",
        "KONSEAL": "A form of capsule for inclosing a dose of medicine that isoffensive, caustic, or the like.",
        "KONZE": "A large African antelope (Alcelaphus Lichtensteini), allied tothe hartbeest, but having shorter and flatter horns, and lacking ablack patch on the face.",
        "KOODOO": "A large South African antelope (Strepsiceros kudu). The maleshave graceful spiral horns, sometimes four feet long. The generalcolor is reddish or grayish brown, with eight or nine white bands oneach side, and a pale dorsal stripe. The old males become dark bluishgray, due to the skin showing through the hair. The females arehornless. Called also nellut. [Written also kudu.]",
        "KOOKOOM": "The oryx or gemsbok. [Written also kookaam.]",
        "KOOLOKAMBA": "A west African anthropoid ape (Troglodytes koolokamba, or T.Aubryi), allied to the chimpanzee and gorilla, and, in some respects,intermediate between them.",
        "KOOLSLAA": "See Coleslaw.",
        "KOORD": "See Kurd.",
        "KOORDISH": "See Kurdish.",
        "KOORILIAN": "Same as Kurilian.",
        "KOP": "Hill; mountain. [South Africa]",
        "KOPECK": "A small Russian coin. One hundred kopecks make a rouble, worthabout sixty cents. [Written also kopek, copec, and copeck.]",
        "KOPJE": "A hillock; a small kop. [South Africa]",
        "KORAN": "The Scriptures of the Mohammedans, containing the professedrevelations to Mohammed; -- called also Alcoran. [Written also Kuranor Quran.]",
        "KORIN": "The gazelle.",
        "KORRIGUM": "A West African antelope (Damalis Senegalensis), allied to thesassaby. It is reddish gray, with a black face, and a black stripe onthe outside of the legs above the knees.",
        "KOSHER": "Ceremonially clean, according to Jewish law; --applied to food,esp. to meat of animals slaughtered according to the requirements ofJewish law. Opposed to tref. Hence, designating a shop, store, house,etc., where such food is sold or used.",
        "KOSMOS": "See Cosmos. Gladstone.",
        "KOTOW": "The prostration made by mandarins and others to theirsuperiors, either as homage or worship, by knocking the forehead onthe ground. There are degrees in the rite, the highest beingexpressed by three knockings. [China]kowtow S. W. Williams.",
        "KOULAN": "A wild horse (Equus, or Asinus, onager) inhabiting the plantsof Central Asia; -- called also gour, khur, and onager. [Written alsokulan.]",
        "KOUMISS": "An intoxicating fermented or distilled liquor originally madeby the Tartars from mare's or camel's milk. It can be obtained fromany kind of milk, and is now largely made in Europe. [Written alsokoumyss, kumiss, kumish, and kumys.]Koumiss has from time immemorial served the Tartar instead of wine orspirits. J. H. Newman.",
        "KOUSSO": "An Abyssinian rosaceous tree (Brayera anthelmintica), theflowers of which are used as a vermifuge. [Written also cusso andkosso.]",
        "KOWTOW": "The same as Kotow.I have salaamed and kowtowed to him. H. James.",
        "KRA": "A long-tailed ape (Macacus cynomolgus) of India and Sumatra. Itis reddish olive, spotted with black, and has a black tail.",
        "KRAIT": "A very venomous snake of India (Bungarus coeruleus), allied tothe cobra. Its upper parts are bluish or brownish black, often withnarrow white streaks; the belly is whitish.",
        "KRAKEN": "A fabulous Scandinavian sea monster, often represented asresembling an island, but sometimes as resembling an immense octopus.To believe all that has been said of the sea serpent or kraken, wouldbe credulity; to reject the possibility of their existence, would bepresumption. Goldsmith.Like a kraken huge and black. Longfellow.",
        "KRAKOWIAK": "A lively Polish dance. See Cracovienne.",
        "KRAMERIA": "A genus of spreading shrubs with many stems, from one speciesof which (K. triandra), found in Peru, rhatany root, used as amedicine, is obtained.",
        "KRAMERIC": "Pertaining to, or derived from, Krameria (rhatany); as,krameric acid, usually called ratanhia-tannic acid.",
        "KRANG": "The carcass of a whale after the blubber has been removed.[Written also crang and kreng.]",
        "KRANGING HOOK": "A hook for holding the blubber while cutting it away. [Writtenalso cranging hook.]",
        "KREATIC": "See Creatic.",
        "KREATIN": "See Creatin.",
        "KREATININ": "See Creatinin.",
        "KREEL": "See Creel.",
        "KREMLIN": "The citadel of a town or city; especially, the citadel ofMoscow, a large inclosure which contains imperial palaces,cathedrals, churches, an arsenal, etc. [Russia]",
        "KREMS": "A variety of white lead. See Krems lead, under Lead, n.",
        "KRENG": "See Krang.",
        "KREOSOTE": "See Creosote.",
        "KREUTZER": "A small copper coin formerly used in South Germany; also, asmall Austrian copper coin. [Written also kreuzer.]",
        "KRIEGSSPIEL": "A game of war, played for practice, on maps. Farrow.",
        "KRIS": "A Malay dagger. See Creese.",
        "KRISHNA": "The most popular of the Hindoo divinities, usually held to bethe eighth incarnation of the god Vishnu.",
        "KRITARCHY": "The rule of the judges over Israel.Samson, Jephthah, Gideon, and other heroes of the kritarchy. Southey.",
        "KROKIDOLITE": "See Crocidolite.",
        "KRONE": "A coin of Denmark, Norway, and Sweden, of the value of abouttwenty-eight cents. See Crown, n., 9.",
        "KROOMAN": "One of a negro tribe of Liberia and the adjacent coast, whosemembers are much employed on shipboard.",
        "KRULLER": "See Cruller.",
        "KRUPP GUN": ". A breech-loading steel cannon manufactured at the works ofFriedrich Krupp, at Essen in Prussia. Guns of over eight-inch boreare made up of several concentric cylinders; those of a smaller sizeare forged solid. Knight.",
        "KRUPPIZE": "To treat by, or subject to, the Krupp process.",
        "KRYOLITE": "See Cryolite.",
        "KRYPTON": "An inert gaseous element of the argon group, occurring in airto the extent of about one volume in a million. It was discovered byRamsay and Travers in 1898. Liquefying point, -- 152º C.; symbol, Kr;atomic weight, 83.0.",
        "KSAR": "See Czar.",
        "KUDA": "The East Indian tapir. See Tapir.",
        "KUDOS": "Glory; fame; renown; praise. W. H. Russel.",
        "KUDU": "See Koodoo.",
        "KUFIC": "See Cufic.",
        "KUKANG": "The slow lemur. See Lemur.",
        "KUKLUX": "The name adopted in the southern part of the United States by asecret political organization, active for several years after theclose of the Civil War, and having for its aim the repression of thepolitical power of the freedmen; -- called also Kuklux Klan.",
        "KULAN": "See Koulan.",
        "KULTURKAMPF": "Lit., culture war; -- a name, originating with Virchow (1821 --1902), given to a struggle between the the Roman Catholic Church andthe German government, chiefly over the latter's efforts to controleducational and ecclesiastical appointments in the interest of thepolitical policy of centralization. The struggle began with thepassage by the Prussian Diet in May, 1873, of the so-called May laws,or Falk laws, aiming at the regulation of the clergy. Oppositioneventually compelled the government to change its policy, and from1880 to 1887 laws virtually nullifying the May laws were enacted.",
        "KUMMEL": "A Russian and German liqueur, consisting of a sweetened spiritflavored with caraway seeds.",
        "KUMQUAT": "A small tree of the genus Citrus (C. Japonica) growing in Chinaand Japan; also, its small acid, orange-colored fruit used forpreserves.",
        "KUPFERNICKEL": "Copper-nickel; niccolite. See Niccolite.",
        "KURD": "A native or inhabitant of a mountainous region of Western Asiabelonging to the Turkish and Persian monarchies. [Written alsoKoord.]",
        "KURDISH": "Of or pertaining to the Kurds. [Written also Koordish.]",
        "KURILIAN": "Of or pertaining to the Kurile Islands, a chain of islands inthe Pacific ocean, extending from the southern extremity ofKamschatka to Yesso.-- n.",
        "KURO-SIWO": "See Japan Current, above.",
        "KURSAAL": "A public hall or room, for the use of visitors at wateringplaces and health resorts in Germany.",
        "KUSIMANSE": "A carnivorous animal (Crossarchus obscurus) of tropical Africa.It its allied to the civets. Called also kusimansel, and mangue.",
        "KUSKUS": "See Vetiver.",
        "KUSSIER": "(Mus.) A Turkish instrument of music, with a hollow bodycovered with skin, over which five strings are stretched. [Writtenalso kussir.]",
        "KUTAUSS": "The India civet (Viverra zibetha).",
        "KUTCH": "The packet of vellum leaves in which the gold is first beateninto thin sheets.",
        "KY": "Kine. [Scot.] See Kee, Kie, and Kine.",
        "KYACK": "A pack sack to be swung on either side of a packsaddle.[Western U. S.]",
        "KYANITE": "See Cyanite.",
        "KYANIZE": "To render (wood) proof against decay by saturating with asolution of corrosive sublimate in open tanks, or under pressure.",
        "KYANOPHYLL": "Same as Cyanophyll.",
        "KYAR": "Cocoanut fiber, or the cordage made from it. See Coir.",
        "KYAW": "A daw. [Scot.]",
        "KYD": "p. p. of Kythe.",
        "KYDDE": "imp. of Kythe, to show. [Obs.] Chaucer.",
        "KYKE": "To look steadfastly; to gaze. [Obs.] [Written also kike, keke.]This Nicholas sat ever gaping upright, As he had kyked on the newemoon. Chaucer.",
        "KYLEY": "A variety of the boomerang.",
        "KYLOES": "The cattle of the Hebrides, or of the Highlands. [Scot.] Sir W.Scott.",
        "KYMNEL": "See Kimnel. [Obs.] Chapman.",
        "KYMOGRAPH": "An instrument for measuring, and recording graphically, thepressure of the blood in any of the blood vessels of a living animal;-- called also kymographion.",
        "KYMOGRAPHIC": "Of or pertaining to a kymograph; as, a kymographic tracing.",
        "KYMRIC": "See Cymric, a. & n.",
        "KYMRY": "See Cymry.",
        "KYNREDE": "Kindred. [Obs.] Chaucer.",
        "KYNURENIC": "Pertaining to, or designating, an acid obtained from the urineof dogs. By decomposition the acid yields a nitrogenous base (calledkynurin) and carbonic acid. [Written also cynurenic.]",
        "KYRIE": "See Kyrie eleison.",
        "KYRIE ELEISON": "Greek words, meaning \"Lord, have mercy upon us,\" used in theMass, the breviary offices, the litany of the saints, etc. Addis &Arnold.",
        "KYRIELLE": "A litany beginning with the words. \"Kyrie eleison.\" Shipley.",
        "KYRIOLOGICAL": "Serving to denote objects by conventional signs or alphabeticalcharacters; as, the original Greek alphabet of sixteen letters wascalled kyriologic, because it represented the pure elementary sounds.See Curiologic. [Written also curiologic and kuriologic.]",
        "KYTHE": "To come into view; to appear. [Scot.]It kythes bright . . . because all is dark around it. Sir W. Scott.",
        "KYTOMITON": "See Karyomiton.",
        "KYTOPLASMA": "See Karyoplasma."
    };

}