
class CategoryQ {
  static Map<String, String> categoryQ = {
    "Q": ", the seventeenth letter of the English alphabet, has but one sound (that of k), and is always followed by u, the two letter stogether being sounded like kw, except in some words in which the uis silent. See Guide to Pronunciation, § 249. Q is not found inAnglo-Saxon, cw being used instead of qu; as in cwic, quick; cwen,queen. The name (ku) is from the French ku, which is from the Latinname of the same letter; its form is from the Latin, which derivedit, through a Greek alphabet, from the Phoenician, the ultimateorigin being Egyptian. Etymologically, q or qu is most nearly relatedto a (ch, tch), p, q, and wh; as in cud, quid, L. equus, ecus, horse,Gr. equine, hippic; L. quod which, E. what; L. aquila, E. eaqle; E.kitchen, OE. kichene, AS. cycene, L. coquina.",
    "QUA": "In so far as; in the capacity or character of; as.It is with Shelley's biographers qua biographers that we have to deal. London Spectator.",
    "QUA-BIRD": "The American night heron. See under Night.",
    "QUAB": "An unfledged bird; hence, something immature or unfinished.Ford.",
    "QUACHA": "The quagga.",
    "QUACK": "A boastful pretender to medical skill; an empiric; an ignorant practitioner.",
    "QUACK GRASS": "See Quitch grass.",
    "QUACKERY": "The acts, arts, or boastful pretensions of a quack; falsepretensions to any art; empiricism. Carlyle.",
    "QUACKISH": "Like a quack; boasting; characterized by quackery. Burke.",
    "QUACKISM": "Quackery. Carlyle.",
    "QUACKLE": "To suffocate; to choke. [Prov. Eng.]",
    "QUACKSALVER": "One who boasts of his skill in medicines and salves, or of theefficacy of his prescriptions; a charlatan; a quack; a mountebank.[Obs.] Burton.",
    "QUAD": "A quadrat.",
    "QUADRABLE": "That may be sqyared, or reduced to an equivalent square; --said of a surface when the area limited by a curve can be exactlyfound, and expressed in a finite number of algebraic terms.",
    "QUADRAGENARIOUS": "Consisting of forty; forty years old.",
    "QUADRAGENE": "An indulgence of forty days, corresponding to the forty days ofancient canonical penance.",
    "QUADRAGESIMA": "The forty days of fast preceding Easter; Lent. QuadragesimaSunday, the first Sunday in Lent, about forty days before Easter.",
    "QUADRAGESIMAL": "Belonging to Lent; used in Lent; Lenten.",
    "QUADRAGESIMALS": "Offerings formerly made to the mother church of a diocese onMid-Lent Sunday.",
    "QUADRANGLE": "A plane figure having four angles, and consequently four sides;any figure having four angles.",
    "QUADRANGULAR": "Having four angles, and consequently four sides; tetragonal.-- Quad*ran\"gu*lar*ly, adv.",
    "QUADRANS": "A fourth part of the coin called an as. See 3d As, 2.",
    "QUADRANT": "The quarter of a circle, or of the circumference of a circle,an arc of 90º, or one subtending a right angle at the center.",
    "QUADRANTAL": "Of or pertaining to a quadrant; also, included in the fourthpart of a circle; as, quadrantal space. Quadrantal triangle, aspherical triangle having one side equal to a quadrant or arc of 90º.-- Quadrantal versor, a versor that expresses rotation through oneright angle.",
    "QUADRAT": "A block of type metal lower than the letters, -- used inspacing and in blank lines. [Abbrev. quad.]",
    "QUADRATE": "A plane surface with four equal sides and four right angles; asquare; hence, figuratively, anything having the outline of a square.At which command, the powers militant That stood for heaven, inmighty quadrate joined. Milton.",
    "QUADRATIC": "Tetragonal.",
    "QUADRATICS": "That branch of algebra which treats of quadratic equations.",
    "QUADRATOJUGAL": "The quadratojugal bone. Quadratojugal bone (Anat.), a bone atthe base of the lower jaw in many animals.",
    "QUADRATRIX": "A curve made use of in the quadrature of other curves; as thequadratrix, of Dinostratus, or of Tschirnhausen.",
    "QUADRATURE": "The act of squaring; the finding of a square having the samearea as some given curvilinear figure; as, the quadrature of acircle; the operation of finding an expression for the area of afigure bounded wholly or in part by a curved line, as by a curve, twoordinates, and the axis of abscissas.",
    "QUADRENNIALLY": "Once in four years.",
    "QUADRENNIUM": "A space or period of four years.",
    "QUADRI-": "A combining form meaning four, four times, fourfold; as,quadricapsular, having four capsules.",
    "QUADRIBASIC": "Same as Tetrabasic.",
    "QUADRIBLE": "Quadrable. [R.]",
    "QUADRIC": "Of or pertaining to the second degree.",
    "QUADRICAPSULAR": "Having four capsules.",
    "QUADRICEPS": "The great extensor muscle of the knee, divided above into fourparts which unite in a single tendon at the knee.",
    "QUADRICIPITAL": "Of or pertaining to the quadriceps.",
    "QUADRICORN": "Any quadricornous animal.",
    "QUADRICORNOUS": "Having four horns, or hornlike organs; as, a quadricornousbeetle.",
    "QUADRICOSTATE": "Having four ribs.",
    "QUADRIDENTATE": "Having four teeth; as, a quadridentate leaf.",
    "QUADRIENNIAL": "Same as Quadrennial.",
    "QUADRIFARIOUS": "Arranged in four rows or ranks; as, quadrifarious leaves.Loudon.",
    "QUADRIFID": "Divided, or deeply cleft, into four parts; as, a quadrifidperianth; a quadrifid leaf.",
    "QUADRIFURCATED": "Having four forks, or branches.",
    "QUADRIGA": "A car or chariot drawn by four horses abreast.",
    "QUADRIGENARIOUS": "Consisting of four hundred.",
    "QUADRIJUGATE": "Same as Quadrijugous.",
    "QUADRIJUGOUS": "Pinnate, with four pairs of leaflets; as, a quadrijugous leaf.",
    "QUADRILATERAL": "Having four sides, and consequently four angles; quadrangular.",
    "QUADRILATERALNESS": "The property of being quadrilateral.",
    "QUADRILITERAL": "Consisting of four letters.",
    "QUADRILLE": "A game played by four persons with forty cards, being theremainder of an ordinary pack after the tens, nines, and eights arediscarded. Hoyle.",
    "QUADRILLION": "According to the French notation, which is followed also uponthe Continent and in the United States, a unit with fifteen ciphersannexed; according to the English notation, the number produced byinvolving a million to the fourth power, or the number represented bya unit with twenty-four ciphers annexed. See the Note underNumeration.",
    "QUADRILOCULAR": "Having four cells, or cavities; as, a quadrilocular heart.",
    "QUADRIN": "A small piece of money, in value about a farthing, or a halfcent. [Obs.]",
    "QUADRINODAL": "Possessing four nodes; as, quadrinodal curves.",
    "QUADRINOMIAL": "A polynomial of four terms connected by the signs plus orminus.",
    "QUADRINOMICAL": "Quadrinomial.",
    "QUADRINOMINAL": "Quadrinomial. Sir W. R. Hamilton.",
    "QUADRIPARTITE": "Divided into four parts.",
    "QUADRIPARTITELY": "In four parts.",
    "QUADRIPARTITION": "A division or distribution by four, or into four parts; also, ataking the fourth part of any quantity or number.",
    "QUADRIPENNATE": "Having four wings; -- said of insects.",
    "QUADRIPHYLLOUS": "Having four leaves; quadrifoliate.",
    "QUADRIREME": "A galley with four banks of oars or rowers.",
    "QUADRISECTION": "A subdivision into four parts.",
    "QUADRISULCATE": "Having four hoofs; as, a quadrisulcate foot; a quadrisulcateanimal.",
    "QUADRISYLLABLE": "A word consisting of four syllables. De Quincey.",
    "QUADRIVALENCE": "The quality or state of being quadrivalent; tetravalence.",
    "QUADRIVALENT": "Having a valence of four; capable of combining with, beingreplaced by, or compared with, four monad atoms; tetravalent; -- saidof certain atoms and radicals; thus, carbon and silicon arequadrivalent elements.",
    "QUADRIVALVE": "Dehiscent into four similar parts; four-valved; as, aquadrivalve pericarp.",
    "QUADRIVALVULAR": "Having four valves; quadrivalve.",
    "QUADRIVIAL": "Having four ways meeting in a point. B. Jonson.",
    "QUADRIVIUM": "The four \"liberal arts,\" arithmetic, music, geometry, andastronomy; -- so called by the schoolmen. See Trivium.",
    "QUADROON": "The offspring of a mulatto and a white person; a personquarter-blooded. [Written also quarteron, quarteroon, and quateron.]",
    "QUADROXIDE": "A tetroxide. [R.]",
    "QUADRUMANA": "A division of the Primates comprising the apes and monkeys; --so called because the hind foot is usually prehensile, and the greattoe opposable somewhat like a thumb. Formerly the Quadrumana wereconsidered an order distinct from the Bimana, which last included manalone.",
    "QUADRUMANE": "One of the Quadrumana.",
    "QUADRUMANOUS": "Having four hands; of or pertaining to the Quadrumana.",
    "QUADRUPED": "Having four feet.",
    "QUADRUPEDAL": "Having four feet; of or pertaining to a quadruped.",
    "QUADRUPLANE": "An aëroplane with four superposed main supporting surfaces.",
    "QUADRUPLE": "Fourfold; as, to make quadruple restitution; a quadruplealliance. Quadruple time (Mus.), that in which each measure isdivided into four equal parts.",
    "QUADRUPLEX": "Fourfold; folded or doubled twice. Quadruplex system (ElectricTelegraph), a system by which four messages, two in each direction,may be sent simultaneously over the wire.",
    "QUADRUPLICATE": "To make fourfold; to double twice; to quadruple.",
    "QUADRUPLICATION": "The act of making fourfold; a taking four times the simple sumor amount.",
    "QUADRUPLY": "To a fourfold quantity; so as to be, or cause to be, quadruple;as, to be quadruply recompensed.",
    "QUAERE": "Inquire; question; see; -- used to signify doubt or to suggestinvestigation.",
    "QUAESTOR": "Same as Questor.",
    "QUAFF": "To drink with relish; to drink copiously of; to swallow inlarge draughts. \"Quaffed off the muscadel.\" Shak.They eat, they drink, and in communion sweet Quaff immortality andjoy. Milton.",
    "QUAFFER": "One who quaffs, or drinks largely.",
    "QUAG": "A quagmire. [R.] \"Crooked or straight, through quags or thornydells.\" Cowper.",
    "QUAGGA": "A South African wild ass (Equus, or Hippotigris, quagga). Theupper parts are reddish brown, becoming paler behind and behind andbeneath, with dark stripes on the face, neck, and fore part of thebody.",
    "QUAGGY": "Of the nature of a quagmire; yielding or trembling under thefoot, as soft, wet earth; spongy; boggy. \"O'er the watery strath, orquaggy moss.\" Collins.",
    "QUAGMIRE": "Soft, wet, miry land, which shakes or yields under the feet. \"Aspot surrounded by quagmires, which rendered it difficult of access.\"Palfrey.",
    "QUAIL": "To cause to fail in spirit or power; to quell; to crush; tosubdue. [Obs.] Spenser.",
    "QUAILY": "The upland plover. [Canadian]",
    "QUAINTLY": "In a quaint manner. Shak.",
    "QUAINTNESS": "The quality of being quaint. Pope.",
    "QUAIR": "A quire; a book. [Obs.] \" The king's quhair.\" James I. (ofScotland).",
    "QUAKE": "To cause to quake. [Obs.] Shak.",
    "QUAKERESS": "A woman who is a member of the Society of Friends.",
    "QUAKERISH": "Like or pertaining to a Quaker; Quakerlike.",
    "QUAKERISM": "The peculiar character, manners, tenets, etc., of the Quakers.",
    "QUAKERLIKE": "Like a Quaker.",
    "QUAKERLY": "Resembling Quakers; Quakerlike; Quakerish. Macaulay.",
    "QUAKERY": "Quakerism. [Obs.] Hallywell.",
    "QUAKETAIL": "A wagtail.",
    "QUAKINESS": "The state of being quaky; liability to quake.",
    "QUAKING": "a. & n. from Quake, v. Quaking aspen (Bot.), an Americanspecies of poplar (Populus tremuloides), the leaves of which tremblein the lightest breeze. It much resembles the European aspen. SeeAspen.-- Quaking bog, a bog of forming peat so saturated with water thatit shakes when trodden upon.-- Quaking grass. (Bot.) (a) One of several grasses of the genusBriza, having slender-stalked and pendulous ovate spikelets, whichquake and rattle in the wind. Briza maxima is the large quakinggrass; B. media and B. minor are the smaller kinds. (b) Rattlesnakegrass (Glyceria Canadensis).",
    "QUAKINGLY": "In a quaking manner; fearfully. Sir P. Sidney.",
    "QUAKY": "Shaky, or tremulous; quaking.",
    "QUALIFIABLE": "Capable of being qualified; abatable; modifiable. Barrow.",
    "QUALIFICATIVE": "That which qualifies, modifies, or restricts; a qualifying termor statement.How many qualificatives, correctives, and restrictives he insertethin this relation. Fuller.",
    "QUALIFICATOR": "An officer whose business it is to examine and prepare causesfor trial in the ecclesiastical courts.",
    "QUALIFIEDLY": "In the way of qualification; with modification orqualification.",
    "QUALIFIEDNESS": "The state of being qualified.",
    "QUALIFIER": ", One who, or that which, qualifies; that which modifies,reduces, tempers or restrains.",
    "QUALITATIVE": "Relating to quality; having the character of quality.-- Qual\"i*ta*tive*ly, adv. Qualitative analysis (Chem.), analysiswhich merely determines the constituents of a substance without anyregard to the quantity of each ingredient; -- contrasted withquantitative analysis.",
    "QUALITIED": "Furnished with qualities; endowed. [Obs.] \"He was wellqualitied.\" Chapman.",
    "QUALMISH": "Sick at the stomach; affected with nausea or sickly languor;inclined to vomit. Shak.-- Qualm\"ish*ly, adv.-- Qualm\"ish*ness, n.",
    "QUAMASH": "See Camass.",
    "QUAMOCLIT": "Formerly, a genus of plants including the cypress vine(Quamoclit vulgaris, now called Ipomoea Quamoclit). The genus is nowmerged in Ipomoea.",
    "QUANDARY": "A state of difficulty or perplexity; doubt; uncertainty.",
    "QUANDONG": "The edible drupaceous fruit of an Australian tree (Fusanusacuminatus) of the Sandalwood family; -- called also quandang.",
    "QUANDY": "The old squaw. [Local, U. S.]",
    "QUANNET": "A flat file having the handle at one side, so as to be usedlike a plane.",
    "QUANT": "A punting pole with a broad flange near the end to prevent itfrom sinking into the mud; a setting pole.",
    "QUANTIC": "A homogeneous algebraic function of two or more variables, ingeneral containing only positive integral powers of the variables,and called quadric, cubic, quartic, etc., according as it is of thesecond, third, fourth, fifth, or a higher degree. These are furthercalled binary, ternary, quaternary, etc., according as they containtwo, three, four, or more variables; thus, the quantic is a binarycubic.",
    "QUANTIFICATION": "Modification by a reference to quantity; the introduction ofthe element of quantity.The quantification of the predicate belongs in part to Sir WilliamHamilton; viz., in its extension to negative propositions. DeQuincey.",
    "QUANTIFY": "To modify or qualify with respect to quantity; to fix orexpress the quantity of; to rate.",
    "QUANTITATIVE": "Relating to quantity.-- Quan\"ti*ta*tive*ly, adv. Quantitative analysis (Chem.), analysiswhich determines the amount or quantity of each ingredient of asubstance, by weight or by volume; -- contrasted with qualitativeanalysis.",
    "QUANTITIVE": "Estimable according to quantity; quantitative. Sir K. Digby.",
    "QUANTITIVELY": "So as to be measurable by quantity; quantitatively.",
    "QUANTIVALENCE": "Valence. [Archaic]",
    "QUANTIVALENT": "Of or pertaining to quantivalence. [Archaic]",
    "QUANTUM": "A definite portion of a manifoldness, limited by a mark or by aboundary. W. K. Clifford. Quantum meruit ( Etym: [L., as much as hemerited] (Law), a count in an action grounded on a promise that thedefendant would pay to the plaintiff for his service as much as heshould deserve.-- Quantum sufficit (, or Quantum suff. Etym: [L., as much suffices](Med.), a sufficient quantity.-- Quantum valebat ( Etym: [L., as much at it was worth] (Law), acount in an action to recover of the defendant, for goods sold, asmuch as they were worth. Blackstone.",
    "QUAP": "To quaver. [Obs.] See Quob.",
    "QUAQUAVERSAL": "Dipping toward all points of the compass round a center, asbeds of lava round a crater.",
    "QUAR": "A quarry. [Prov. Eng.] B. Jonson.",
    "QUARANTINE": "The period of forty days during which the widow had theprivilege of remaining in the mansion house of which her husband diedseized. Quarantine flag, a yellow flag hoisted at the fore of avessel or hung from a building, to give warning of an infectiousdisease; -- called also the yellow jack, and yellow flag.",
    "QUARL": "A medusa, or jellyfish. [R.]The jellied quarl that flings At once a thousand streaming stings. J.R. Drake.",
    "QUARREL": "Any small square or quadrangular member; as:(a) A square of glass, esp. when set diagonally.(b) A small opening in window tracery, of which the cusps, etc., makethe form nearly square.(c) A square or lozenge-shaped paving tile.",
    "QUARRELET": "A little quarrel. See 1st Quarrel, 2. [Obs.] \"Quarrelets ofpearl [teeth].\" Herrick.",
    "QUARRELING": "Engaged in a quarrel; apt or disposed to quarrel; as,quarreling factions; a quarreling mood.-- Quar\"rel*ing*ly, adv.",
    "QUARRELLOUS": "Quarrelsome. [Obs.] [Written also quarrellous.] Shak.",
    "QUARRELSOME": "Apt or disposed to quarrel; given to brawls and contention;easily irritated or provoked to contest; irascible; choleric.",
    "QUARRIED": "Provided with prey.Now I am bravely quarried. Beau. & Fl.",
    "QUARRIER": "A worker in a stone quarry.",
    "QUARRY": "Same as 1st Quarrel. [Obs.] Fairfax.",
    "QUARRY-FACED": "Having a face left as it comes from the quarry and not smoothedwith the chisel or point; -- said of stones.",
    "QUARRY-MAN": "A man who is engaged in quarrying stones; a quarrier.",
    "QUART": "The fourth part; a quarter; hence, a region of the earth.[Obs.]Camber did possess the western quart. Spenser.",
    "QUARTAN": "Of or pertaining to the fourth; occurring every fourth day,reckoning inclusively; as, a quartan ague, or fever.",
    "QUARTANE": "Butane, each molecule of which has four carbon atoms.",
    "QUARTATION": "The act, process, or result (in the process of parting) ofalloying a button of nearly pure gold with enough silver to reducethe fineness so as to allow acids to attack and remove all metalsexcept the gold; -- called also inquartation. Compare Parting.",
    "QUARTE": "Same as 2d Carte.",
    "QUARTENE": "Same as Butylene.",
    "QUARTENYLIC": "Pertaining to, or designating, an acid of the acrylic acidseries, metameric with crotonic acid, and obtained as a colorlessliquid; -- so called from having four carbon atoms in the molecule.Called also isocrotonic acid.",
    "QUARTER": "The encampment on one of the principal passages round a placebesieged, to prevent relief and intercept convoys.(i) (Naut.) The after-part of a vessel's side, generallycorresponding in extent with the quarter-deck; also, the part of theyardarm outside of the slings.(j) (Her.) One of the divisions of an escutcheon when it is dividedinto four portions by a horizontal and a perpendicular line meetingin the fess point.",
    "QUARTER ROUND": "An ovolo.",
    "QUARTER-DECK": "That part of the upper deck abaft the mainmast, including thepoop deck when there is one.",
    "QUARTER-SAW": "To saw (a log) into quarters; specif., to saw into quarters andthen into boards, as by cutting alternately from each face of aquarter, to secure lumber that will warp relatively little or showthe grain advantageously.",
    "QUARTERAGE": "A quarterly allowance.",
    "QUARTERFOIL": "An ornamental foliation having four lobes, or foils.",
    "QUARTERHUNG": "Having trunnions the axes of which lie below the bore; -- saidof a cannon.",
    "QUARTERING": "Coming from a point well abaft the beam, but not directlyastern; -- said of waves or any moving object.",
    "QUARTERLY": "A periodical work published once a quarter, or four times in ayear.",
    "QUARTERMASTER": "An officer whose duty is to provide quarters, provisions,storage, clothing, fuel, stationery, and transportation for aregiment or other body of troops, and superintend the supplies.",
    "QUARTERON": "A quarter; esp., a quarter of a pound, or a quarter of ahundred. Piers Plowman.",
    "QUARTERPACE": "A platform of a staircase where the stair turns at a rightangle only. See Halfpace.",
    "QUARTERSTAFF": "A long and stout staff formerly used as a weapon of defense andoffense; -- so called because in holding it one hand was placed inthe middle, and the other between the middle and the end.",
    "QUARTIC": "Of the fourth degree.",
    "QUARTILE": "Same as Quadrate.",
    "QUARTINE": "A supposed fourth integument of an ovule, counting from theoutside.",
    "QUARTO": "Having four leaves to the sheet; of the form or size of aquarto.",
    "QUARTRIDGE": "Quarterage. [Obs.]",
    "QUARTZ": "A form of silica, or silicon dioxide (SiO2), occurring inhexagonal crystals, which are commonly colorless and transparent, butsometimes also yellow, brown, purple, green, and of other colors;also in cryptocrystalline massive forms varying in color and degreeof transparency, being sometimes opaque.",
    "QUARTZIFEROUS": "Consisting chiefly of quartz; containing quartz.",
    "QUARTZITE": "Massive quartz occurring as a rock; a metamorphosed sandstone;-- called also quartz rock.",
    "QUARTZOID": "A form of crystal common with quartz, consisting of two six-sided pyramids, base to base.",
    "QUARTZOSE": "Containing, or resembling, quartz; partaking of the nature orqualities of quartz.",
    "QUARTZOUS": "Quarzose.",
    "QUARTZY": "Quartzose.",
    "QUAS": "A kind of beer. Same as Quass.",
    "QUASH": "Same as Squash.",
    "QUASHEE": "A negro of the West Indies.",
    "QUASI": "As if; as though; as it were; in a manner sense or degree;having some resemblance to; qualified; -- used as an adjective, or aprefix with a noun or an adjective; as, a quasi contract, an impliedcontract, an obligation which has arisen from some act, as if from acontract; a quasi corporation, a body that has some, but not all, ofthe peculiar attributes of a corporation; a quasi argument, thatwhich resembles, or is used as, an argument; quasi historical,apparently historical, seeming to be historical.",
    "QUASI CORPORATION": "A corporation consisting of a person or body of personsinvested with some of the qualities of an artificial person, thoughnot expressly incorporated, esp. the official of certain municipaldivisions such as counties, schools districts, and the towns of someStates of the United States, certain church officials, as achurchwarden, etc.",
    "QUASIMODO": "The first Sunday after Easter; Low Sunday.",
    "QUASS": "A thin, sour beer, made by pouring warm water on rye or barleymeal and letting it ferment, -- much used by the Russians. [writtenalso quas.]",
    "QUASSATION": "The act of shaking, or the state of being shaken. Gayton.",
    "QUASSIA": "The wood of several tropical American trees of the orderSimarubeæ, as Quassia amara, Picræna excelsa, and Simaruba amara. Itis intensely bitter, and is used in medicine and sometimes as asubstitute for hops in making beer.",
    "QUASSIN": "The bitter principle of quassia, extracted as a whitecrystalline substance; -- formerly called quassite. [Written alsoquassiin, and quassine.]",
    "QUAT": "To satiate; to satisfy. [Prov. Eng.]",
    "QUATA": "The coaita.",
    "QUATCH": "Squat; flat. [Obs.] Shak.",
    "QUATER-COUSIN": "A cousin within the first four degrees of kindred.",
    "QUATERNARY": "Later than, or subsequent to, the Tertiary; Post-tertiary; as,the Quaternary age, or Age of man.",
    "QUATERNATE": "Composed of, or arranged in, sets of four; quaternary; as,quaternate leaves.",
    "QUATERNION": "The quotient of two vectors, or of two directed right lines inspace, considered as depending on four geometrical elements, and asexpressible by an algebraic symbol of quadrinomial form.",
    "QUATERON": "See 2d Quarteron.",
    "QUATORZAIN": "A poem of fourteen lines; a sonnet. R. H. Stoddard.",
    "QUATORZE": "The four aces, kings, queens, knaves, or tens, in the game ofpiquet; -- so called because quatorze counts as fourteen points.",
    "QUATRAIN": "A stanza of four lines rhyming alternately. Dryden.",
    "QUATRE": "A card, die. or domino, having four spots, or pips",
    "QUATTROCENTO": "The fifteenth century, when applied to Italian art orliterature; as, the sculpture of the quattrocento; quattrocentostyle. --Quat`tro*cen\"tist (#), n.",
    "QUATUOR": "A quartet; -- applied chiefly to instrumental compositions.",
    "QUAVE": "See Quaver. [Obs.]",
    "QUAVEMIRE": "See Quagmire. [Obs.]",
    "QUAVER": "To utter with quavers.We shall hear her quavering them . . . to some sprightly airs of theopera. Addison.",
    "QUAVERER": "One who quavers; a warbler.",
    "QUAY": "A mole, bank, or wharf, formed toward the sea, or at the sideof a harbor, river, or other navigable water, for convenience inloading and unloading vessels. [Written also key.]",
    "QUAYAGE": "Wharfage. [Also keyage.]",
    "QUAYD": "p. p. of Quail. [Obs.] Spenser.",
    "QUE": "A half farthing. [Obs.]",
    "QUEACH": "A thick, bushy plot; a thicket. [Obs.] Chapman.",
    "QUEASILY": "In a queasy manner.",
    "QUEASINESS": "The state of being queasy; nausea; qualmishness; squeamishness.Shak.",
    "QUEBEC GROUP": "The middle of the three groups into which the rocks of theCanadian period have been divided in the American Lower Siluriansystem. See the Chart of Geology.",
    "QUEBRACHO": "A Chilian apocynaceous tree (Aspidosperma Quebracho); also, itsbark, which is used as a febrifuge, and for dyspnoea of the lung, orbronchial diseases; -- called also white quebracho, to distinguish itfrom the red quebracho, a Mexican anacardiaceous tree (LoxopterygiumLorentzii) whose bark is said to have similar properties. J. Smith(Dict. Econ. Plants).",
    "QUEBRITH": "Sulphur. [Obs.]",
    "QUEEN": "The most powerful, and except the king the most important,piece in a set of chessmen.",
    "QUEEN OLIVE": "Properly, a kind of superior olive grown in the region ofSeville, Spain. It is large size and oblong shape with a small butlong pit; it is cured when green, keeps well, and has a delicateflavor. Loosely, any olive of similar character.",
    "QUEEN TRUSS": "A truss framed with queen-posts; a queen-post truss.",
    "QUEEN-POST": "One of two suspending posts in a roof truss, or other framedtruss of similar form. See King-post.",
    "QUEENCRAFT": "Craft or skill in policy on the part of a queen.Elizabeth showed much queencraft in procuring the votes of thenobility. Fuller.",
    "QUEENDOM": "The dominion, condition, or character of a queen. Mrs.Browning.",
    "QUEENFISH": "A California sciænoid food fish (Seriphys politus). The back isbluish, and the sides and belly bright silvery. Called also kingfish.",
    "QUEENHOOD": "The state, personality, or character of a queen; queenliness.Tennyson.",
    "QUEENING": "Any one of several kinds of apples, as summer queening, scarletqueening, and early queening. An apple called the queening wascultivated in England two hundred years ago.",
    "QUEENLINESS": "The quality of being queenly; the; characteristic of a queen;stateliness; eminence among women in attractions or power.",
    "QUEENLY": "Like, becoming, or suitable to, a queen.",
    "QUEENSHIP": "The state, rank, or dignity of a queen.",
    "QUEENSLAND NUT": "The nut of an Australian tree (Macadamia ternifolia). It isabout an inch in diameter, and contains a single round edible seed,or sometimes two hemispherical seeds. So called from Queensland inAustralia.",
    "QUEER": "Counterfeit money. [Slang] To shove the queer, to putcounterfeit money in circulation. [Slang]",
    "QUEERISH": "Rather queer; somewhat singular.",
    "QUEERLY": "In a queer or odd manner.",
    "QUEERNESS": "The quality or state of being queer.",
    "QUEEST": "The European ringdove (Columba palumbus); the cushat. [Writtenalso quist, queeze, quice, queece.] See Ringdove.",
    "QUEGH": "A drinking vessel. See Quaich.",
    "QUEINT": "See Quaint. [Obs.]",
    "QUEINTISE": "See Quaintise. [Obs.] Chaucer.",
    "QUELL": "Murder. [Obs.] Shak.",
    "QUELLIO": "A ruff for the neck. [Obs.] B. Jonson.",
    "QUELQUECHOSE": "A trifle; a kickshaw. Donne.",
    "QUEME": "To please. [Obs.] Chaucer.",
    "QUEMEFUL": "Kindly; merciful. [Obs.] Wyclif.",
    "QUENCH": "To become extinguished; to go out; to become calm or cool. [R.]Dost thou think in time She will not quench! Shak.",
    "QUENCHABLE": "Capable of being quenched.",
    "QUENCHER": "One who, or that which, quenches. Hammond.",
    "QUENCHLESS": "Incapable of being quenched; inextinguishable; as, quenchlessfire or fury. \"Once kindled, quenchless evermore.\" Byron.",
    "QUENELLE": "A kind of delicate forcemeat, commonly poached and used as adish by itself or for garnishing.",
    "QUENOUILLE TRAINING": "A method of training trees or shrubs in the shape of a cone ordistaff by tying down the branches and pruning.",
    "QUERCITANNIC": "Pertaining to, or designating, a tannic acid found in oak barkand extracted as a yellowish brown amorphous substance.",
    "QUERCITE": "A white crystalline substance, C6H7(OH)5, found in acorns, thefruit of the oak (Quercus). It has a sweet taste, and is regarded asa pentacid alcohol.",
    "QUERCITIN": "A yellow crystalline substance, occurring quite widelydistributed in the vegetable kingdom, as is apple-tree bark, horse-chestnut leaves, etc., but originally obtained by the decompositionof quercitrin. Called also meletin.",
    "QUERCITRIN": "A glucoside extracted from the bark of the oak (Quercus) as abitter citron-yellow crystalline substance, used as a pigment andcalled quercitron.",
    "QUERCUS": "A genus of trees constituted by the oak. See Oak.",
    "QUERELE": "A complaint to a court. See Audita Querela. [Obs.] Ayliffe.",
    "QUERENT": "A complainant; a plaintiff.",
    "QUERIMONIOUS": "Complaining; querulous; apt to complain.-- Quer`i*mo\"ni*ous*ly, adv.-- Quer`i*mo\"ni*ous*ness, n.",
    "QUERIMONY": "A complaint or complaining. [Obs.] E. Hall.",
    "QUERIST": "One who inquires, or asks questions. Swift.",
    "QUERKEN": "To stifle or choke. [Prov. Eng.] Halliwell.",
    "QUERL": "To twirl; to turn or wind round; to coil; as, to querl a cord,thread, or rope. [Local, U.S.]",
    "QUERN": "A mill for grinding grain, the upper stone of which was turnedby hand; -- used before the invention of windmills and watermills.Shak.They made him at the querne grind. Chaucer.",
    "QUERPO": "The inner or body garments taken together. See Cuerpo. Dryden.",
    "QUERRY": "A groom; an equerry. [Obs.]",
    "QUERULENTIAL": "Querulous. [R.]",
    "QUESAL": "The long-tailed, or resplendent, trogon (Pharomachus mocinno,formerly Trogon resplendens), native of Southern Mexico and CentralAmerica. Called alsoquetzal, and golden trogon.",
    "QUEST": "To search for; to examine. [R.] Sir T. Herbert.",
    "QUESTANT": "One who undertakes a quest; a seeker. [Obs.] Shak.",
    "QUESTER": "One who seeks; a seeker. [Obs.]",
    "QUESTIONABILITY": "The state or condition of being questionable. Stallo.",
    "QUESTIONABLENESS": "The quality or state of being questionable, doubtful, orsuspicious.",
    "QUESTIONABLY": "In a questionable manner.",
    "QUESTIONARY": "Inquiring; asking questions; testing. \"Questionary epistles.\"Pope.",
    "QUESTIONER": "One who asks questions; an inquirer. \"Little time for idlequestioners.\" Tennyson.",
    "QUESTIONIST": "A candidate for honors or degrees who is near the time of hisexamination.",
    "QUESTIONLESS": "Unquestioning; incurious. [R.]",
    "QUESTIONNAIRE": "= Questionary, above.",
    "QUESTMAN": "One legally empowered to make quest of certain matters, esp. ofabuses of weights and measures. Specifically:(a) A churchwarden's assistant; a sidesman. Blount. [Obs.](b) A collector of parish rents. Blount. [Obs.]",
    "QUESTMONGER": "One who lays informations, and encourages petty lawsuits.[Obs.] Bacon.",
    "QUESTOR": "An officer who had the management of the public treasure; areceiver of taxes, tribute, etc.; treasurer of state. [Written alsoquæstor.]",
    "QUESTORSHIP": "The office, or the term of office, of a questor.",
    "QUESTRIST": "A seeker; a pursuer. [Obs.] \"Hot questrists after him.\" Shak.",
    "QUESTUARY": "Studious of profit. [Obs.] Sir T. Browne.",
    "QUET": "The common guillemot. [Prov. Eng.]",
    "QUEUE": "To fasten, as hair, in a queue.",
    "QUEY": "A heifer. [Scot.]",
    "QUI VIVE": "The challenge of a French sentinel, or patrol; -- used like theEnglish challenge: \"Who comes there\" To be on the qui vive, to be onguard; to be watchful and alert, like a sentinel.",
    "QUIB": "A quip; a gibe.",
    "QUIBBLER": "One who quibbles; a caviler; also, a punster.",
    "QUIBBLINGLY": "Triflingly; evasively.",
    "QUICA": "A small South American opossum (Didelphys quica), native ofGuiana and Brazil. It feeds upon insects, small birds, and fruit.",
    "QUICE": "See Queest.",
    "QUICH": "To stir. [Obs.]He could not move nor quich at all. Spenser.",
    "QUICHUAN": "Designating, or pertaining to, a linguistic stock of SouthAmerican Indians, including the majority of the civilized tribes ofthe ancient Peruvian Empire with some wild tribes never subjugated bythe Incas. Most of these Indians are short, but heavy and strong.They are brachycephalic and of remarkably low cranial capacity.Nevertheless, they represent one of the highest of native Americancivilizations, characterized by agricultural, military, andadministrative skill rather than by science or literature, althoughthey were adept potters, weavers, and goldsmiths, and preserved bythe aid of the mnemonic quipu a body of legendary lore in partwritten down since the introduction of writing.",
    "QUICK": "In a quick manner; quickly; promptly; rapidly; with haste;speedily; without delay; as, run quick; get back quick.If we consider how very quick the actions of the mind are performed.Locke.",
    "QUICK-SCENTED": "Acute of smell.",
    "QUICK-SIGHTED": "Having quick sight or acute discernment; quick to see or todiscern. Locke. --Quick\"-sight`ed*ness, n.",
    "QUICK-WITTED": "Having ready wit Shak.",
    "QUICK-WITTEDNESS": "Readiness of wit. \"Celtic quick-wittedness.\" M. Arnold.",
    "QUICKBEAM": "See Quicken tree.",
    "QUICKEN": "To shorten the radius of (a curve); to make (a curve) sharper;as, to quicken the sheer, that is, to make its curve more pronounced.",
    "QUICKEN TREE": "The European rowan tree; -- called also quickbeam, andquickenbeam. See Rowan tree.",
    "QUICKENER": "One who, or that which, quickens.",
    "QUICKENING": "The first motion of the fetus in the womb felt by the mother,occurring usually about the middle of the term of pregnancy. It hasbeen popularly supposed to be due to the fetus becoming possessed ofindependent life.",
    "QUICKENS": "Quitch grass.",
    "QUICKHATCH": "The wolverine.",
    "QUICKLIME": "Calcium oxide; unslacked lime; -- so called because when wet itdevelops great heat. See 4th Lime, 2.",
    "QUICKLY": "Speedily; with haste or celerity; soon; without delay; quick.",
    "QUICKSAND": "Sand easily moved or readily yielding to pressure; especially,a deep mass of loose or moving sand mixed with water, sometimes foundat the mouth of a river or along some coasts, and very dangerous,from the difficulty of extricating a person who begins sinking intoit.Life hath quicksands, -- Life hath snares! Longfellow.",
    "QUICKSET": "A living plant set to grow, esp. when set for a hedge;specifically, the hawthorn.",
    "QUICKSILVER": "The metal mercury; -- so called from its resemblance to liquidsilver. Quicksilver horizon, a mercurial artificial horizon. Seeunder Horizon.-- Quicksilver water, a solution of mercury nitrate used inartificial silvering; quick water.",
    "QUICKSILVERED": "Overlaid with quicksilver, or with an amalgam of quicksilverand tinfoil.",
    "QUICKSILVERING": "The mercury and foil on the back of a looking-glass.",
    "QUICKSTEP": "A lively, spirited march; also, a lively style of dancing.",
    "QUID": "A portion suitable to be chewed; a cud; as, a quid of tobacco.",
    "QUIDAM": "Somebody; one unknown. Spenser.",
    "QUIDDANY": "A confection of quinces, in consistency between a sirup andmarmalade.",
    "QUIDDATIVE": "Constituting, or containing, the essence of a thing;quidditative.",
    "QUIDDIT": "A subtilty; an equivocation. [Obs.] Shak.By some strange quiddit or some wrested clause. Drayton.",
    "QUIDDITATIVE": "Quiddative.",
    "QUIDDLE": "To spend time in trifling employments, or to attend to usefulsubjects in an indifferent or superficial manner; to dawdle.",
    "QUIDNUNC": "One who is curious to know everything that passes; one whoknows, or pretends to know, all that is going on. \"The idle storiesof quidnuncs.\" Motley.",
    "QUIESCE": "To be silent, as a letter; to have no sound. M. Stuart.",
    "QUIESCENT": "Not sounded; silent; as, y is quiescent in \"day\" and \"say.\"",
    "QUIESCENTLY": "In a quiescent manner.",
    "QUIET": "To become still, silent, or calm; -- often with down; as, besoon quieted down.",
    "QUIETAGE": "Quietness. [Obs.] Spenser.",
    "QUIETER": "One who, or that which, quiets.",
    "QUIETISM": "The system of the Quietists, who maintained that religionconsists in the withdrawal of the mind from worldly interests andanxieties and its constant employment in the passive contemplation ofGod and his attributes.",
    "QUIETIST": "One of a sect of mystics originated in the seventeenth centuryby Molinos, a Spanish priest living in Rome. See Quietism.",
    "QUIETISTIC": "Of or pertaining to the Quietists, or to Quietism.",
    "QUIETNESS": "The quality or state of being quiet; freedom from noise,agitation, disturbance, or excitement; stillness; tranquillity;calmness.I would have peace and quietness. Shak.",
    "QUIETSOME": "Calm; still. [Obs.] Spenser.",
    "QUIETUDE": "Rest; repose; quiet; tranquillity. Shelley.",
    "QUIETUS": "Final discharge or acquittance, as from debt or obligation;that which silences claims; (Fig.) rest; death.When he himself might his quietus make With a bare bodkin. Shak.",
    "QUILLAIA BARK": "The bark of a rosaceous tree (Quillaja Saponaria), native ofChili. The bark is finely laminated, and very heavy with alkalinesubstances, and is used commonly by the Chilians instead of soap.Also called soap bark.",
    "QUILLBACK": "An American fresh-water fish (Ictiobus, or Carpiodes,cyprinus); -- called also carp sucker, sailfish, spearfish, andskimback.",
    "QUILLED": "Furnished with quills; also, shaped like quills. \"A sharp-quilled porcupine.\" Shak. Quilled suture (Surg.), a variety of stitchin which the threads after being passed deeply through the edges of awound are secured about two quills or bodies of similar shape, inorder to produce a suitable degree of pressure.",
    "QUILLET": "Subtilty; nicety; quibble. \"Nice, sharp quillets of the law.\"Shak.",
    "QUILLWORT": "Any plant or species of the genus Isoetes, cryptogamous plantswith a cluster of elongated four-tubed rushlike leaves, rising from acorm, and containing spores in their enlarged and excavated bases.There are about seventeen American species, usually growing in themud under still, shallow water. So called from the shape of the shapeof the leaves.",
    "QUILT": "Anything that is quilted; esp., a quilted bed cover, or a skirtworn by women; any cover or garment made by putting wool, cotton,etc., between two cloths and stitching them together; also, any outerbed cover.The beds were covered with magnificent quilts. Arbuthnot.",
    "QUILTER": "One who, or that which, quilts.",
    "QUILTING": "A coating of strands of rope for a water vessel.",
    "QUIN": "A European scallop (Pecten opercularis), used as food. [Prov.Eng.]",
    "QUINALDINE": "A colorless liquid of a slightly pungent odor, C9H6N.CH3, firstobtained as a condensation product of aldehyde and aniline, andregarded as a derivative of quinoline; -- called also methylquinoline. [Written also chinaldine.]",
    "QUINARY": "Consisting of five; arranged by fives. Boyle. Quinary system(Zoöl.), a fanciful classification based on the hypothesis that eachgroup contains five types.",
    "QUINATE": "Growing in sets of five; -- said especially of leaves composedof five leaflets set at the end of a common petiole.",
    "QUINAZOL": "A complex nitrogenous base related to cinnoline. [Written alsochinazol.]",
    "QUINCE": "a quince tree or shrub. Japan quince (Bot.), an Eastern Asiaticshrub (Cydonia, formerly Pyrus, Japonica) and its very fragrant butinedible fruit. The shrub has very showy flowers, usually red, butsometimes pink or white, and is much grown for ornament.-- Quince curculio (Zoöl.), a small gray and yellow curculio(Conotrachelus cratægi) whose larva lives in quinces.-- Quince tree (Bot.), the small tree (Cydonia vulgaris) whichproduces the quince.",
    "QUINCEWORT": "The squinancy. Called also quinsywort.",
    "QUINCH": "To stir; to wince. [Obs.] Spenser.",
    "QUINCUNCIAL": "Having the leaves of a pentamerous calyx or corolla soimbricated that two are exterior, two are interior, and the other hasone edge exterior and one interior; as, quincuncial æstivation.Quincuncial phyllotaxy (Bot.), an arrangement of five leaves in aspiral, each leaf two fifths of a circle from the next.",
    "QUINCUNCIALLY": "In the manner or order of a quincunx.",
    "QUINCUNX": "The position of planets when distant from each other fivesigns, or 150º. Hutton.",
    "QUINDECAGON": "A plane figure with fifteen angles, and consequently fifteensides.",
    "QUINDECEMVIR": "One of a sacerdotal college of fifteen men whose chief duty wasto take care of the Sibylline books.",
    "QUINDECEMVIRATE": "The body or office of the quindecemviri.",
    "QUINDECONE": "An unsaturated hydrocarbon, C15H26, of the valylene series,produced artificially as an oily liquid. [Written also quindekone.]",
    "QUINDECYLIC": "Pertaining to, or designating, an acid of the fatty acidseries, containing fifteen atoms of carbon; called also pentadecylicacid.",
    "QUINDEM": "A fifteenth part. [Obs.]",
    "QUINDISM": "A fifteenth. [Obs.] Prynne.",
    "QUINHYDRONE": "A green crystalline substance formed by the union of quinonewith hydroquinone, or as an intermediate product in the oxidation ofhydroquinone or the reduction of quinone. [Written also chinhydrone.]",
    "QUINIA": "Quinine.",
    "QUINIBLE": "An interval of a fifth; also, a part sung with such intervals.[Obs.] \"He sang . . . a loud quynyble.\" Chaucer.",
    "QUINIC": "Pertaining to, derived from, or connected with, quinine andrelated compounds; specifically, designating a nonnitrogenous acidobtained from cinchona bark, coffee, beans, etc., as a whitecrystalline substance. [Written also chinic, kinic.]",
    "QUINICINE": "An uncrystallizable alkaloid obtained by the action of heatfrom quinine, with which it is isomeric.",
    "QUINIDINE": "An alkaloid isomeric with, and resembling, quinine, found incertain species of cinchona, from which it is extracted as a bitterwhite crystalline substance; conchinine. It is used somewhat as afebrifuge. [Written also chinidine.]",
    "QUININE": "An alkaloid extracted from the bark of several species ofcinchona (esp. Cinchona Calisaya) as a bitter white crystallinesubstance, C20H24N2O2. Hence, by extension (Med.), any of the saltsof this alkaloid, as the acetate, chloride, sulphate, etc., employedas a febrifuge or antiperiodic. Called also quinia, quinina, etc.[Written also chinine.]",
    "QUININIC": "Pertaining to, or designating, a nitrogenous acid obtained as ayellow crystalline substance by the oxidation of quinine.",
    "QUINIZARIN": "A yellow crystalline substance produced artificially. It isisomeric with alizarin.",
    "QUINIZINE": "any one of a series of nitrogenous bases, certain of which areused as antipyretics.",
    "QUINNAT": "The California salmon (Oncorhynchus choicha); -- called alsochouicha, king salmon, chinnook salmon, and Sacramento salmon. It isof great commercial importance. [Written also quinnet.]",
    "QUINOA": "The seeds of a kind of goosewort (Chenopodium Quinoa), used inChili and Peru for making porridge or cakes; also, food thus made.",
    "QUINOGEN": "A hypothetical radical of quinine and related alkaloids.",
    "QUINOIDINE": "A brownish resinous substance obtained as a by-product in thetreatment of cinchona bark. It consists of a mixture of severalalkaloids. [Written also chinoidine.]",
    "QUINOLINE": "A nitrogenous base, C9H7N obtained as a pungent colorlessliquid by the distillation of alkaloids, bones, coal tar, etc. It thenucleus of many organic bodies, especially of certain alkaloids andrelated substances; hence, by extension, any one of the series ofalkaloidal bases of which quinoline proper is the type. [Written alsochinoline.]",
    "QUINOLOGIST": "One who is versed in quinology.",
    "QUINOLOGY": "The science which treats of the cultivation of the cinchona,and of its use in medicine.",
    "QUINONE": "A crystalline substance, C6H4O2 (called also benzoketone),first obtained by the oxidation of quinic acid and regarded as adouble ketone; also, by extension, any one of the series of whichquinone proper is the type. [Written also chinone, kinone.]",
    "QUINOVIC": "Pertaining to, or designating, a crystalline acid obtained fromsome varieties of cinchona bark. [Written also chinovic, andkinovic.]",
    "QUINOVIN": "An amorphous bitter glucoside derived from cinchona and otherbarks. Called also quinova bitter, and quinova. [Written alsochinovin, and kinovin.]",
    "QUINOXALINE": "Any one of a series of complex nitrogenous bases obtained bythe union of certain aniline derivatives with glyoxal or with certainketones. [Written also chinoxaline.]",
    "QUINOXYL": "The hypothetical radical of certain quinone derivatives relatedto rhodizonic acid.",
    "QUINOYL": "A radical of which quinone is the hydride, analogous to phenyl.[Written also kinoyl.]",
    "QUINQUAGESIMA": "Fiftieth. Quinquagesima Sunday, the Sunday which is thefiftieth day before Easter, both days being included in thereckoning; -- called also Shrove Sunday.",
    "QUINQUANGULAR": "Having five angles or corners.",
    "QUINQUARTICULAR": "Relating to the five articles or points; as, thequinquarticular controversy between Arminians and Calvinists. [Obs.]Bp. Sanderson.",
    "QUINQUE FOLIOLATE": "Having five leaflets. Gray.",
    "QUINQUE-": "A combining form meaning five, five times, fivefold; as,quinquefid, five-cleft; quinquedentate, five-toothed.",
    "QUINQUEANGLED": "Having five angles; quinquangular.",
    "QUINQUEFARIOUS": "Arranged in five vertical rows; pentastichous. Gray.",
    "QUINQUEFID": "Sharply cut about halfway to the middle or base into fivesegments; as, a quinquefid leaf or corolla.",
    "QUINQUELITERAL": "Consisting of five letters.",
    "QUINQUELOBED": "Same as Quinquelobate.",
    "QUINQUELOCULAR": "Having five cells or loculi; five-celled; as, a quinquelocularpericarp.",
    "QUINQUENERVED": "Having five nerves; -- said of a leaf with five nearly equalnerves or ribs rising from the end of the petiole.",
    "QUINQUENNALIA": "Public games celebrated every five years.",
    "QUINQUENNIAL": "Occurring once in five years, or at the end of every fiveyears; also, lasting five years. A quinquennial event.",
    "QUINQUENNIUM": "Space of five years.",
    "QUINQUEPARTITE": "Divided into five parts almost to the base.",
    "QUINQUEREME": "A galley having five benches or banks of oars; as, an Athenianquinquereme.",
    "QUINQUESYLLABLE": "A word of five syllables.",
    "QUINQUEVIR": "One of five commissioners appointed for some special object.",
    "QUINQUINA": "Peruvian bark.",
    "QUINQUIVALENT": "Same as Pentavalent.",
    "QUINSY": "An inflammation of the throat, or parts adjacent, especially ofthe fauces or tonsils, attended by considerable swelling, painful andimpeded deglutition, and accompanied by inflammatory fever. Itsometimes creates danger of suffocation; -- called also squinancy,and squinzey.",
    "QUINT": "The interval of a fifth.",
    "QUINTAIN": "An object to be tilted at; -- called also quintel. [Writtenalso quintin.]",
    "QUINTAN": "Occurring as the fifth, after four others also, occurring everyfifth day, reckoning inclusively; as, a quintan fever.-- n. (Med.)",
    "QUINTEL": "See Quintain.",
    "QUINTESSENCE": "To distil or extract as a quintessence; to reduce to aquintessence. [R.] Stirling. \"Truth quintessenced and raised to thehighest power.\" J. A. Symonds.",
    "QUINTESSENTIAL": "Of the nature of a quintessence; purest. \"Quintessentialextract of mediocrity.\" G. Eliot.",
    "QUINTIC": "Of the fifth degree or order.-- n. (Alg.)",
    "QUINTILE": "The aspect of planets when separated the fifth part of thezodiac, or 72º. Hutton.",
    "QUINTILLLION": "According to the French notation, which is used on theContinent and in America, the cube of a million, or a unit witheighteen ciphers annexed; according to the English notation, a numberproduced by involving a million to the fifth power, or a unit withthirty ciphers annexed. See the Note under Numeration.",
    "QUINTIN": "See Quintain.",
    "QUINTINE": "The embryonic sac of an ovule, sometimes regarded as aninnermost fifth integument. Cf. Quartine, and Tercine.",
    "QUINTOLE": "A group of five notes to be played or sung in the time of fourof the same species.",
    "QUINTROON": "The off-spring of an octoroon and a white person.",
    "QUINTUPLE": "Multiplied by five; increased to five times the amount;fivefold. Quintuple time (Mus.), a time having five beats in ameasure. It is seldom used.",
    "QUINZAINE": "The fifteenth day after a feast day, including both in thereckoning. [Written also quinzain.]",
    "QUINZE": "A game at cards in which the object is to make fifteen points.",
    "QUIP": "A smart, sarcastic turn or jest; a taunt; a severe retort; agibe.Quips, and cranks, and wanton wiles. Milton.He was full of joke and jest, But all his merry quips are o'er.Tennyson.",
    "QUIPO": "Same as Quipu.",
    "QUIPU": "A contrivance employed by the ancient Peruvians, Mexicans,etc., as a substitute for writing and figures, consisting of a maincord, from which hung at certain distances smaller cords of variouscolors, each having a special meaning, as silver, gold, corn,soldiers. etc. Single, double, and triple knots were tied in thesmaller cords, representing definite numbers. It was chiefly used forarithmetical purposes, and to register important facts and events.[Written also quipo.] Tylor.The mysterious science of the quipus . . . supplied the Peruvianswith the means of communicating their ideas to one another, and oftransmitting them to future generations. Prescott.",
    "QUIRBOILLY": "Leather softened by boiling so as to take any required shape.Upon drying, it becomes exceedingly hard, and hence was formerly usedfor armor. [Obs.] \"His jambeux were of quyrboilly.\" Chaucer.",
    "QUIRE": "See Choir. [Obs.] Spenser.A quire of such enticing birds. Shak.",
    "QUIRINAL": "Of, pertaining to, or designating, the hill Collis Quirinalis,now Monte Quirinale (one of the seven hills of Rome), or a modernroyal place situated upon it. Also used substantively.",
    "QUIRISTER": "A chorister. See Chorister. [R.] Thomson.",
    "QUIRITATION": "A crying for help. [Obs.] Bp. Hall.",
    "QUIRITE": "One of the Quirites.",
    "QUIRITES": "Roman citizens.",
    "QUIRK": "A piece of ground taken out of any regular ground plot orfloor, so as to make a court, yard, etc.; -- sometimes written quink.Gwilt.",
    "QUIRKED": "Having, or formed with, a quirk or quirks.",
    "QUIRKISH": ", Consisting of quirks; resembling a quirk. Barrow.",
    "QUIRKY": "Full of quirks; tricky; as, a quirky lawyer.",
    "QUIRL": "See Querl.",
    "QUIRPELE": "The Indian ferret.",
    "QUIRT": "A rawhide whip plaited with two thongs of buffalo hide T.Roosevelt.",
    "QUISH": "See Cuish.",
    "QUIT": "Any one of numerous species of small passerine birds native oftropical America. See Banana quit, under Banana, and Guitguit.",
    "QUITCH": "Same as Quitch grass.",
    "QUITCH GRASS": "A perennial grass (Agropyrum repens) having long runningrootstalks, by which it spreads rapidly and pertinaciously, and sobecomes a troublesome weed. Also called couch grass, quick grass,quick grass, twitch grass. See Illustration in Appendix.",
    "QUITCLAIM": "A release or relinquishment of a claim; a deed of release; aninstrument by which some right, title, interest, or claim, which oneperson has, or is supposed to have, in or to an estate held byhimself or another, is released or relinquished, the grantorgenerally covenanting only against persons who claim under himself.",
    "QUITE": "See Quit. [Obs.] Chaucer.",
    "QUITLY": "Quite. [Obs.] Chaucer.",
    "QUITRENT": "A rent reserved in grants of land, by the payment of which thetenant is quit from other service. Blackstone.",
    "QUITS": "See the Note under Quit, a.",
    "QUITTABLE": "Capable of being quitted.",
    "QUITTAL": "Return; requital; quittance. [Obs.]",
    "QUITTANCE": "To repay; to requite. [Obs.] Shak.",
    "QUITTOR": "A chronic abscess, or fistula of the coronet, in a horse'sfoot, resulting from inflammation of the tissues investing the coffinbone.",
    "QUITTURE": "A discharge; an issue. [Obs.]To cleanse the quitture from thy wound. Chapman.",
    "QUIVER": "Nimble; active. [Obs.] \" A little quiver fellow.\" Shak.",
    "QUIVERINGLY": "With quivering motion.",
    "QUIXOTIC": "Like Don Quixote; romantic to extravagance; absurdly chivalric;apt to be deluded. \"Feats of quixotic gallantry.\" Prescott.",
    "QUIXOTICALLY": "In a quixotic way.",
    "QUIXOTISM": "That form of delusion which leads to extravagant and absurdundertakings or sacrifices in obedience to a morbidly romantic idealof duty or honor, as illustrated by the exploits of Don Quixote inknight-errantry.",
    "QUIXOTRY": "Quixotism; visionary schemes.",
    "QUIZ": "To conduct a quiz. See Quiz, n., 4. [U.S.]",
    "QUIZZER": "One who quizzes; a quiz.",
    "QUIZZICAL": "Relating to quizzing: given to quizzing; of the nature of aquiz; farcical; sportive.-- Quiz\"zic*al*ly, adv.",
    "QUIZZISM": "The act or habit of quizzing.",
    "QUO WARRANTO": "A writ brought before a proper tribunal, to inquire by whatwarrant a person or a corporation acts, or exercises certain powers.Blackstone.",
    "QUOB": "To throb; to quiver. [Local & Vulgar]",
    "QUOD": "A quadrangle or court, as of a prison; hence, a prison. [Slang]\"Flogged or whipped in quod.\" T. Hughes.",
    "QUODDIES": "Herring taken and cured or smoked near Quoddy Head, Maine, ornear the entrance of Passamaquoddy Ray.",
    "QUODLIBET": "A medley improvised by several performers.",
    "QUODLIBETARIAN": "One who discusses any subject at pleasure.",
    "QUODLIBETICAL": "Not restricted to a particular subject; discussed for curiosityor entertainment.-- Quod`li*bet\"ic*al*ly, adv.",
    "QUOIF": "See Coif. Shak.",
    "QUOIFFURE": "See Coiffure.",
    "QUOIL": "See Coil. [Obs.]",
    "QUOIN": "Originally, a solid exterior angle, as of a building; now,commonly, one of the selected pieces of material by which the corneris marked.",
    "QUOIT": "A game played with quoits. Shak.",
    "QUOKE": "imp. of Quake. Chaucer.",
    "QUOLL": "A marsupial of Australia (Dasyurus macrurus), about the size ofa cat.",
    "QUONDAM": "Having been formerly; former; sometime. \"This is the quondamking.\" Shak.",
    "QUOOK": "imp. of Quake. [Obs.] Spenser.",
    "QUOP": "See Quob.",
    "QUORUM": "Such a number of the officers or members of any body as iscompetent by law or constitution to transact business; as, a quorumof the House of Representatives; a constitutional quorum was notpresent.",
    "QUOTA": "A proportional part or share; the share or proportion assignedto each in a division. \"Quota of troops and money.\" Motley.",
    "QUOTABLE": "Capable or worthy of being quoted; as, a quotable writer; aquotable sentence.-- Quot`a*bit\"i*ty, n. Poe.",
    "QUOTATION": "The naming or publishing of the current price of stocks, bonds,or any commodity; also the price named.",
    "QUOTATIONIST": "One who makes, or is given to making, quotations.The narrow intellectuals of quotationists. Milton.",
    "QUOTE": "To name the current price of.",
    "QUOTER": "One who quotes the words of another.",
    "QUOTH": "Said; spoke; uttered; -- used only in the first and thirdpersons in the past tenses, and always followed by its nominative,the word or words said being the object; as, quoth I. quoth he. \"Letme not live, quoth he.\" Shak.",
    "QUOTHA": "Indeed; forsooth.To affront the blessed hillside drabs and thieves With mended morals,quotha, -- fine new lives ! Mrs. Browning.",
    "QUOTIDIAN": "Occurring or returning daily; as, a quotidian fever.",
    "QUOTIENT": "The number resulting from the division of one number byanother, and showing how often a less number is contained in agreater; thus, the quotient of twelve divided by four is three.",
    "QUOTIETY": "The relation of an object to number. Krauth-Fleming.",
    "QUOTUM": "Part or proportion; quota. [R.] \"A very small quotum.\" MaxMüller.",
    "QURAN": "See Koran."
  };
}
