class CategoryX {
static Map<String, String> categoryX = {
    "X": "X, the twenty-fourth letter of the English alphabet, has threesounds; a compound nonvocal sound (that of ks), as in wax; a compoundvocal sound (that of gz), as in example; and, at the beginning of aword, a simple vocal sound (that of z), as in xanthic.  See Guide toPronunciation, §§ 217, 270, 271.",
    "X-RAY TUBE": "A vacuum tube suitable for producing Röntgen rays.",
    "XANTHAMIDE": "An amido derivative of xanthic acid obtained as a whitecrystalline substance, C2H5O.CS.NH2; -- called also xanthogen amide.",
    "XANTHATE": "A salt of xanthic; a xanthogenate.",
    "XANTHELASMA": "See Xanthoma.",
    "XANTHIAN": "Of or pertaining to Xanthus, an ancient town on Asia Minor; --applied especially to certain marbles found near that place, and nowin the British Museum.",
    "XANTHIDE": "A compound or derivative of xanthogen. [Archaic]",
    "XANTHIDIUM": "A genus of minute unicellular algæ of the desmids. These alg¨ave a rounded shape and are armed with glochidiate or branchedaculei. Several species occur in ditches, and others are found fossilin flint or hornstone.",
    "XANTHIN": "A white microcrystalline nitrogenous compound, C5H4O2N4,present in muscle tissue, in the liver, spleen, pancreas, and otherorgans, and also in urine (in small quantities) and some urinarycalculi, and in the juices of certain plants; -- so called because itleaves a yellow residue when evaporated to dryness with nitric acid.Xanthine is closely related to uric acid.",
    "XANTHININE": "A complex nitrogenous substance related to urea and uric acid,produced as a white powder; -- so called because it forms yellowsalts, and because its solution forms a blue fluorescence likequinine.",
    "XANTHIUM": "A genus of composite plants in which the scales of theinvolucre are united so as to form a kind of bur; cocklebur; clotbur.",
    "XANTHO-": "A combining form from Gr. xanqo`s yellow; as in xanthocobalticsalts. Used also adjectively in chemistry.",
    "XANTHOCARPOUS": "Having yellow fruit.",
    "XANTHOCHROI": "A division of the Caucasian races, comprising the lighter-colored members.",
    "XANTHOCHROIC": "Having a yellowish or fair complexion; of or pertaining to theXanthochroi.",
    "XANTHOCHROID": "Having a yellowish or fair complexion. -- n.",
    "XANTHOCHROISM": "Abnormal coloration of feathers in which yellow replaces thenormal color, as in certain parrots. It is commonly due to lack ofthe dark pigment which with yellow forms green.",
    "XANTHODONTOUS": "Having yellow teeth.",
    "XANTHOGENATE": "A salt of xanthic acid.",
    "XANTHOGENIC": "Producing a yellow color or compound; xanthic.  See Xanthicacid, under Xanthic.",
    "XANTHOMA": "A skin disease marked by the development or irregular yellowishpatches upon the skin, especially upon the eyelids; -- called alsoxanthelasma.",
    "XANTHOMATOUS": "Of or pertaining to xanthoma.",
    "XANTHOMELANOUS": "Of or pertaining to the lighter division of the Melanochroi, orthose races having an olive or yellow complexion and black hair.",
    "XANTHOPHANE": "The yellow pigment present in the inner segments of the retinain animals.  See Chromophane.",
    "XANTHOPHYLL": "A yellow coloring matter found in yellow autumn leaves, andalso produced artificially from chlorophyll; -- formerly called alsophylloxanthin.",
    "XANTHOPOUS": "Having a yellow stipe, or stem.",
    "XANTHOPROTEIC": "Pertaining to, or derived from, xanthoprotein; showing thecharacters of xanthoprotein; as, xanthoproteic acid; thexanthoproteic reaction for albumin.",
    "XANTHOPROTEIN": "A yellow acid substance formed by the action of hot nitric acidon albuminous or proteid matter. It is changed to a deep orange-yellow color by the addition of ammonia.",
    "XANTHOPUCCINE": "One of three alkaloids found in the root of the yellow puccoon(Hydrastis Canadensis). It is a yellow crystalline substance, andresembles berberine.",
    "XANTHORHAMNIN": "A glucoside extracted from Persian berries as a yellowcrystalline powder, used as a dyestuff.",
    "XANTHORHIZA": "A genus of shrubby ranunculaceous plants of North America,including only the species Xanthorhiza apiifolia, which has roots ofa deep yellow color; yellowroot. The bark is intensely bitter, and issometimes used as a tonic.",
    "XANTHORHOEA": "A genus of endogenous plants, native to Australia, having athick, sometimes arborescent, stem, and long grasslike leaves. SeeGrass tree.",
    "XANTHOSE": "An orange-yellow substance found in pigment spots of certaincrabs.",
    "XANTHOSIS": "The yellow discoloration often observed in cancerous tumors.",
    "XANTHOSPERMOUS": "Having yellow seeds.",
    "XANTHOUS": "Yellow; specifically (Ethnol.), of or pertaining to those racesof man which have yellowish, red, auburn, or brown hair.",
    "XANTHOXYLENE": "A liquid hydrocarbon of the terpene series extracted from theseeds of a Japanese prickly ash (Xanthoxylum pipertium) as anaromatic oil.",
    "XANTHOXYLUM": "A genus of prickly shrubs or small trees, the bark and rots ofwhich are of a deep yellow color; prickly ash.",
    "XEBEC": "A small three-masted vessel, with projecting bow stern andconvex decks, used in the Mediterranean for transporting merchandise,etc. It carries large square sails, or both. Xebecs were formerlyarmed and used by corsairs.",
    "XEME": "An Arctic fork-tailed gull (Xema Sabinii).",
    "XENELASIA": "A Spartan institution which prohibited strangers from residingin Sparta without permission, its object probably being to preservethe national simplicity of manners.",
    "XENIUM": "A present given to a guest or stranger, or to a foreignambassador.",
    "XENODOCHIUM": "A house for the reception of strangers.(b) In the Middle Ages, a room in a monastery for the reception andentertainment of strangers and pilgrims, and for the relief ofpaupers. [Called also Xenodocheion.]",
    "XENODOCHY": "Reception of strangers; hospitality. [R.]",
    "XENOGAMY": "Cross fertilization.",
    "XENOGENETIC": "Of or pertaining to xenogenesis; as, the xenogenetic origin ofmicrozymes. Huxley.",
    "XENOMANIA": "A mania for, or an inordinate attachment to, foreign customs,institutions, manners, fashions, etc. [R.] Saintsbury.",
    "XENOMI": "A suborder of soft-rayed fresh-water fishes of which theblackfish of Alaska (Dallia pectoralis) is the type.",
    "XENON": "A very heavy, inert gaseous element occurring in the atmospherein the proportion of one volume is about 20 millions. It wasdiscovered by Ramsay and Travers in 1898. It can be condensed to aliquid boiling at -109º C., and to a solid which volatilizes withoutmelting. Symbol Xe or X; atomic weight 130.2.",
    "XENOPTERYGII": "A suborder of fishes including Gobiesox and allied genera.These fishes have soft-rayed fins, and a ventral sucker supported infront by the pectoral fins. They are destitute of scales.",
    "XENOTIME": "A native phosphate of yttrium occurring in yellowish-browntetragonal crystals.",
    "XENURINE": "A cabassou.",
    "XENYL": "The radical characteristic of xenylic compounds.",
    "XENYLIC": "Pertaining to, derived from, designating, certain amidocompounds obtained by reducing certain nitro derivatives of diphenyl.",
    "XERAPHIM": "An old money of account in Bombay, equal to three fifths of arupee.",
    "XERES": "Sherry. See Sherry.",
    "XERIF": "A shereef.",
    "XERIFF": "A gold coin formerly current in Egypt and Turkey, of the valueof about 9s. 6d., or about \$2.30; -- also, in Morocco, a ducat.",
    "XERONATE": "A salt of xeronic acid.",
    "XERONIC": "Pertaining to, or designating, an acid, C8H12O4, related tofumaric acid, and obtained from citraconic acid as an oily substancehaving a bittersweet taste; -- so called from its tendency to formits anhydride.",
    "XEROPHAGY": "Among the primitive Christians, the living on a diet of dry food in Lent and on other fasts.",
    "XEROPHILOUS": "Drought-loving; able withstand the absence or lack of moisture.Plants which are peculiarly adapted to dry climates are termed by DeCandolle xerophilous. Goodale.",
    "XEROPHTHALMIA": "An abnormal dryness of the eyeball produced usually by long-continued inflammation and subsequent atrophy of the conjunctiva.",
    "XEROPHTHALMY": "Xerophthalmia.",
    "XIPHIAS": "A genus of fishes comprising the common swordfish.",
    "XIPHIDIUM": "A genus of plants of the order Hæmodraceæ, having two-ranked,sword-shaped leaves.",
    "XIPHIOID": "Of, pertaining to, or resembling, a cetacean of the genusXiphius or family Xiphiidæ.",
    "XIPHIPLASTRON": "The posterior, or fourth, lateral plate in the plastron ofturtles; -- called also xiphisternum.",
    "XIPHIUS": "A genus of cetaceans having a long, pointed, bony beak, usuallytwo tusklike teeth in the lower jaw, but no teeth in the upper jaw.",
    "XIPHODON": "An extinct genus of artiodactylous mammals found in theEuropean Tertiary formations. It had slender legs, didactylous feet,and small canine teeth.",
    "XIPHOIDIAN": "Xiphoid.",
    "XIPHOPHYLLOUS": "Having sword-shaped leaves.",
    "XIPHOSURA": "See Xiphura.",
    "XIPHURA": "Same as Limuloidea. Called also Xiphosura. X ray. See underRay.",
    "XP": "The first two letters of the Greek word XRISTOS, Christ; -- anabbreviation used with the letters separate or, oftener, in amonogram, often inclosed in a circle, as a symbol or emblem ofChrist. It use as an emblem was introduced by Constantine the Great,whence it is known as the Constantinian symbol, or monogram. SeeLabarum.",
    "XYLAMIDE": "An acid amide derivative of xylic acid, obtained as a whitecrystalline substance.",
    "XYLAN": "A gummy substance of the pentosan class, present in woodytissue, and yielding xylose on hydrolysis; wood gum.",
    "XYLANTHRAX": "Wood coal, or charcoal; -- so called in distinction frommineral coal.",
    "XYLATE": "A salt of xylic acid.",
    "XYLEM": "That portion of a fibrovascular bundle which has developed, orwill develop, into wood cells; -- distinguished from phloëm.",
    "XYLENE": "Any of a group of three metameric hydrocarbons of the aromaticseries, found in coal and wood tar, and so named because found incrude wood spirit. They are colorless, oily, inflammable liquids,C6H4.(CH3)2, being dimethyl benzenes, and are called respectivelyorthoxylene, metaxylene, and paraxylene. Called also xylol.",
    "XYLENOL": "Any one of six metameric phenol derivatives of xylene, obtainedas crystalline substances, (CH3)2.C6H3.OH.",
    "XYLETIC": "Pertaining to, or designating, a complex acid related tomesitylenic acid, obtained as a white crystalline substance by theaction of sodium and carbon dioxide on crude xylenol.",
    "XYLIC": "Pertaining to, derived from, or related to, xylene;specifically, designating any one of several metameric acids producedby the partial oxidation of mesitylene and pseudo-cumene.",
    "XYLIDIC": "Pertaining to, or designating, either one of two distinct acidswhich are derived from xylic acid and related compounds, and aremetameric with uvitic acid.",
    "XYLIDINE": "Any one of six metameric hydrocarbons, (CH3)2.C6H3.NH2,resembling aniline, and related to xylene. They are liquids, oreasily fusible crystalline substances, of which three are derivedfrom metaxylene, two from orthoxylene, and one from paraxylene. Theyare called the amido xylenes.",
    "XYLINDEIN": "A green or blue pigment produced by Peziza in certain kinds ofdecayed wood, as the beech, oak, birch, etc., and extracted as anamorphous powder resembling indigo.",
    "XYLITE": "A liquid hydrocarbon found in crude wood spirits.",
    "XYLITONE": "A yellow oil having a geraniumlike odor, produced as a sideproduct in making phorone; -- called also xylite oil.",
    "XYLO-": "A combining form from Gr. xy`lon wood; as in xylogen,xylograph.",
    "XYLOBALSAMUM": "The dried twigs of a Syrian tree (Balsamodendron Gileadense).U. S. Disp.",
    "XYLOCARPOUS": "Bearing fruit which becomes hard or woody.",
    "XYLOCOPA": "A genus of hymenopterous insects including the carpenter. SeeCarpenter bee, under Carpenter.-- Xy*loc\"o*pine, a.",
    "XYLOGRAPH": "An engraving on wood, or the impression from such an engraving;a print by xylography.",
    "XYLOGRAPHER": "One who practices xylography.",
    "XYLOID": "Resembling wood; having the nature of wood.",
    "XYLOIDIN": "A substance resembling pyroxylin, obtained by the action ofnitric acid on starch; -- called also nitramidin.",
    "XYLOL": "Same as Xylene.",
    "XYLOLOGY": "The branch of dendrology treating of the gross and minutestructure of wood.",
    "XYLONITE": "See Zylonite.",
    "XYLOPHAGA": "A genus of marine bivalves which bore holes in wood. They areallied to Pholas.",
    "XYLOPHAGIDES": "A tribe or family of dipterous flies whose larvæ live indecayed wood. Some of the tropical species are very large.",
    "XYLOPHILAN": "One of a tribe of beetles (Xylophili) whose larvæ live ondecayed wood.",
    "XYLOPHILOUS": "Of or pertaining to the xylophilans.",
    "XYLOPHONE": "An instrument common among the Russians, Poles, and Tartars,consisting of a series of strips of wood or glass graduated in lengthto the musical scale, resting on belts of straw, and struck with twosmall hammers. Called in Germany strohfiedel, or straw fiddle.",
    "XYLOPLASTIC": "Formed of wood pulp by molds; relating to casts made of woodpulp in molds.",
    "XYLOPYROGRAPHY": "The art or practice of burning pictures on wood with a hotiron; -- called also poker painting. See Poker picture, under Poker.",
    "XYLOQUINONE": "Any one of a group of quinone compounds obtained respectivelyby the oxidation of certain xylidine compounds. In general they areyellow crystalline substances.",
    "XYLORCIN": "A derivative of xylene obtained as a white crystallinesubstance which on exposure in the air becomes red; -- called alsobetaorcin.",
    "XYLOSE": "An unfermentable sugar of the pentose class, C5H10O5, formed bythe hydrolysis of xylan; wood sugar.",
    "XYLOSTEIN": "A glucoside found in the poisonous berries of a species ofhoneysuckle (Lonicera xylosteum), and extracted as a bitter, white,crystalline substance.",
    "XYLOTILE": "Same as Parkesine.",
    "XYLOTOMIST": "One versed or engaged in xylotomy.",
    "XYLOTOMOUS": "Capable of boring or cutting wood; -- said of many insects.",
    "XYLOTOMY": "Art of preparing sections (transverse, tangential, or radial)of wood, esp. by means of a microtome, for microscopic examination.",
    "XYLOTRYA": "A genus of marine bivalves closely allied to Teredo, andequally destructive to timber. One species (Xylotrya fimbriata) isvery common on the Atlantic coast of the United States.",
    "XYLYL": "Any one of three metameric radicals which are characteristicrespectively of the three xylenes.",
    "XYLYLENE": "Any one of three metameric radicals, CH2.C6H4.CH2, derivedrespectively from the three xylenes. Often used adjectively; as,xylylene alcohol.",
    "XYRIDACEOUS": "Of or pertaining to a natural order (Xyrideæ) of endogenousplants, of which Xyris is the type.",
    "XYRIS": "A genus of endogenous herbs with grassy leaves and small yellowflowers in short, scaly-bracted spikes; yellow-eyed grass. There areabout seventeen species in the Atlantic United States.",
    "XYSTARCH": "An office Dr. W. Smith.",
    "XYSTER": "An instrument for scraping bone."

};}