
class CategoryZ {
    static Map<String, String> categoryZ = {
        "Z": "Z, the twenty-sixth and last letter of the English alphabet, isa vocal consonant. It is taken from the Latin letter Z, which camefrom the Greek alphabet, this having it from a Semitic source. Theultimate origin is probably Egyptian. Etymologically, it is mostclosely related to s, y, and j; as in glass, glaze; E. yoke, Gr.yugum; E. zealous, jealous. See Guide to Pronunciation, §§ 273, 274.",
        "ZA": "An old solfeggio name for B flat; the seventh harmonic, asheard in the or æolian string; -- so called by Tartini. It was longconsidered a false, but is the true note of the chord of the flatseventh. H. W. Poole.",
        "ZABIAN": "See Sabian.",
        "ZACCO": "See Zocco.",
        "ZACHUN": "An oil pressed by the Arabs from the fruit of a small thornytree (Balanites Ægyptiaca), and sold to piligrims for a healingointment. J. Smith (Dict. Econ. Plants).",
        "ZAERTHE": "Same as Zärthe.",
        "ZAFFER": "A pigment obtained, usually by roasting cobalt glance with sandor quartz, as a dark earthy powder. It consists of crude cobaltoxide, or of an impure cobalt arseniate. It is used in porcelainpainting, and in enameling pottery, to produce a blue color, and isoften confounded with smalt, from which, however, it is distinct, asit contains no potash. The name is often loosely applied to mixturesof zaffer proper with silica, or oxides of iron, manganese, etc.[Written also zaffre, and formerly zaffree, zaffar, zaffir.]",
        "ZAIM": "A Turkish chief who supports a mounted militia bearing the samename. Smart.",
        "ZAIMET": "A district from which a Zaim draws his revenue. Smart.",
        "ZAIN": "A horse of a dark color, neither gray nor white, and having nospots. Smart.",
        "ZALAMBDODONT": "Of or pertaining to a tribe (Zalambdodonta) of Insectivora inwhich the molar teeth have but one V-shaped ridge.",
        "ZAMANG": "An immense leguminous tree (Pithecolobium Saman) of Venezuela.Its branches form a hemispherical mass, often one hundred and eightyfeet across. The sweet pulpy pods are used commonly for feedingcattle. Also called rain tree. J. Smith (Dict. Econ. Plants).",
        "ZAMBO": "The child of a mulatto and a negro; also, the child of anIndian and a negro; colloquially or humorously, a negro; a sambo.",
        "ZAMIA": "A genus of cycadaceous plants, having the appearance of lowpalms, but with exogenous wood. See Coontie, and Illust. of Strobile.",
        "ZAMINDAR": "A landowner; also, a collector of land revenue; now, usually, akind of feudatory recognized as an actual proprietor so long as hepays to the government a certain fixed revenue. [Written alsozemindar.] [India]",
        "ZAMITE": "A fossil cycad of the genus Zamia.",
        "ZAMOUSE": "A West African buffalo (Bubalus brachyceros) having short hornsdepressed at the base, and large ears fringed internally with threerows of long hairs. It is destitute of a dewlap. Called also short-horned buffalo, and bush cow.",
        "ZAMPOGNA": "A sort of bagpipe formerly in use among Italian peasants. It isnow almost obsolete. [Written also zampugna.]",
        "ZANDER": "A European pike perch (Stizostedion lucioperca) allied to thewall-eye; -- called also sandari, sander, sannat, schill, and zant.",
        "ZANDMOLE": "The sand mole.",
        "ZANTE": "See Zantewood.",
        "ZANTE CURRANT": "A kind of seedless grape or raisin; -- so called from Zante,one of the Ionian Islands.",
        "ZANTIOT": "A native or inhabitant of Zante, one of the Ionian Islands.",
        "ZANY": "A merry-andrew; a buffoon.Then write that I may follow, and so be Thy echo, thy debtor, thyfoil, thy zany. Donne.Preacher at once, and zany of thy age. Pope.",
        "ZANYISM": "State or character of a zany; buffoonery. Coleridge. H. Morley.",
        "ZAPAS": "See Army organization, above.",
        "ZAPATERA": "A cured olive which has spoiled or is on the verge ofdecomposition; loosely, an olive defective because of bruises,wormholes, or the like.",
        "ZAPHARA": "Zaffer.",
        "ZAPHRENTIS": "An extinct genus of cyathophylloid corals common in thePaleozoic formations. It is cup-shaped with numerous septa, and witha deep pit in one side of the cup.",
        "ZAPOTILLA": "See Sapodilla.",
        "ZAPTIAH": "A Turkish policeman. [Written also zaptieh.]",
        "ZARATHUSTRISM": "See Zoroastrianism.",
        "ZARATITE": "A hydrous carbonate of nickel occurring as an emerald-greenincrustation on chromite; -- called also emerald nickel.",
        "ZAREBA": "An improvised stockade; especially, one made of thorn bushes,etc. [Written also zareeba, and zeriba.] [Egypt]\"Ah,\" he moralizes, \"what wonderful instinct on the part of thislittle creature to surround itself with a zareba like the troopsafter Osman Digma.\" R. Jefferies.",
        "ZARF": "A metallic cuplike stand used for holding a finjan.",
        "ZARNICH": "Native sulphide of arsenic, including sandarach, or realgar,and orpiment.",
        "ZASTRUGI": "Grooves or furrows formed in snow by the action of the wind,and running parallel with the direction of the wind. This formationresults from the erosion of transverse waves previously formed.",
        "ZATI": "A species of macaque (Macacus pileatus) native of India andCeylon. It has a crown of long erect hair, and tuft of radiatinghairs on the back of the head. Called also capped macaque.",
        "ZAUSCHNERIA": "A genus of flowering plants. Zauschneria Californica is asuffrutescent perennial, with showy red flowers much resembling thoseof the garden fuchsia.",
        "ZAX": "A tool for trimming and puncturing roofing states. [Writtenalso sax.]",
        "ZAYAT": "A public shed, or portico, for travelers, worshipers, etc.[Burmah]",
        "ZEA": "A genus of large grasses of which the Indian corn (Zea Mays) isthe only species known. Its origin is not yet ascertained. See Maize.",
        "ZEAL": "To be zealous. [Obs. & R.] Bacon.",
        "ZEALANT": "One who is zealous; a zealot; an enthusiast. [Obs.]To certain zealants, all speech of pacification is odious. Bacon.",
        "ZEALED": "Full of zeal; characterized by zeal. [Obs.] \"Zealed religion.\"Beau. & Fl.",
        "ZEALFUL": "Full of zeal. [R.] Sylvester.",
        "ZEALLESS": "Wanting zeal. Hammond.",
        "ZEALOT": "One who is zealous; one who engages warmly in any cause, andpursues his object with earnestness and ardor; especially, one who isoverzealous, or carried away by his zeal; one absorbed in devotion toanything; an enthusiast; a fanatical partisan.Zealots for the one [tradition] were in hostile array against zealotsfor the other. Sir J. Stephen.In Ayrshire, Clydesdale, Nithisdale, Annandale, every parish wasvisited by these turbulent zealots. Macaulay.",
        "ZEALOTICAL": "Like, or suitable to, a zealot; ardently zealous. [R.] Strype.",
        "ZEALOTISM": "The character or conduct of a zealot; zealotry.",
        "ZEALOTIST": "A zealot. [Obs.] Howell.",
        "ZEALOTRY": "The character and behavior of a zealot; excess of zeal;fanatical devotion to a cause.Enthusiasm, visionariness, seems the tendency of the German; zeal,zealotry, of the English; fanaticism, of the French. Coleridge.",
        "ZEBEC": "See Xebec.",
        "ZEBRA": "Either one of two species of South African wild horsesremarkable for having the body white or yellowish white, andconspicuously marked with dark brown or brackish bands.",
        "ZEBRINE": "Pertaining to, or resembling, the zebra.",
        "ZEBRINNY": "A cross between a male horse and a female zebra.",
        "ZEBU": "A bovine mammal (Ros Indicus) extensively domesticated inIndia, China, the East Indies, and East Africa. It usually has shorthorns, large pendulous ears, slender legs, a large dewlap, and alarge, prominent hump over the shoulders; but these characters varyin different domestic breeds, which range in size from that of thecommon ox to that of a large mastiff.",
        "ZEBUB": "A large noxious fly of Abyssinia, which like the tsetse fly, isdestructive to cattle.",
        "ZECHIN": "See Sequin.",
        "ZECHSTEIN": "The upper division of the Permian (Dyas) of Europe. Theprevailing rock is a magnesian limestone.",
        "ZED": "The letter Z; -- called also zee, and formerly izzard. \"Zed,thou unnecessary letter!\" Shak.",
        "ZEDOARY": "A medicinal substance obtained in the East Indian, having afragrant smell, and a warm, bitter, aromatic taste. It is used inmedicine as a stimulant.",
        "ZEEKOE": "A hippopotamus.",
        "ZEEMAN EFFECT": "The widening and duplication, triplication, etc., of spectrallines when the radiations emanate in a strong magnetic field, firstobserved in 1896 by P. Zeeman, a Dutch physicist, and regarded as animportant confirmation of the electromagnetic theory of light.",
        "ZEHNER": "An Austrian silver coin equal to ten kreutzers, or about fivecents.",
        "ZEIN": "A nitrogenous substance of the nature of gluten, obtained fromthe seeds of Indian corn (Zea) as a soft, yellowish, amorphoussubstance. [Formerly written zeine.]",
        "ZEITGEIST": "The spirit of the time; the general intellectual and moralstate or temper characteristic of any period of time.",
        "ZEMINDAR": "Same as Zamindar.",
        "ZEMNI": "The blind mole rat (Spalax typhlus), native of Eastern Europeand Asia. Its eyes and ears are rudimentary, and its fur is soft andbrownish, more or less tinged with gray. It constructs extensiveburrows.",
        "ZEMSTVO": "In Russia, an elective local district and provincialadministrative assembly. Originally it was composed ofrepresentatives elected by the peasantry, the householders of thetowns, and the landed proprietors. In the reign of Alexander III. thepower of the noble landowners was increased, the peasants allowedonly to elect candidates from whom the governor of the provincenominated the deputy, and all acts of the zemstvo subjected to theapproval of the governor. Theoretically the zemstvo has large powersrelating to taxation, education, public health, etc., but practicallythese powers are in most cases limited to the adjustment of the statetaxation.",
        "ZENANA": "The part of a dwelling appropriated to women. [India]",
        "ZEND": "Properly, the translation and exposition in the Huzvâresh, orliterary Pehlevi, language, of the Avesta, the Zoroastrian sacredwritings; as commonly used, the language (an ancient Persian dialect)in which the Avesta is written.",
        "ZEND-AVESTA": "The sacred writings of the ancient Persian religion, attributedto Zoroaster, but chiefly of a later date.",
        "ZENDIK": "An atheist or unbeliever; -- name given in the East to thosecharged with disbelief of any revealed religion, or accused ofmagical heresies.",
        "ZENICK": "A South African burrowing mammal (Suricata tetradactyla),allied to the civets. It is grayish brown, with yellowish transversestripes on the back. Called also suricat.",
        "ZENIK": "See Zenick.",
        "ZENITHAL": "Of or pertaining to the zenith. \"The deep zenithal blue.\"Tyndall.",
        "ZEOLITE": "A term now used to designate any one of a family of minerals,hydrous silicates of alumina, with lime, soda, potash, or rarelybaryta. Here are included natrolite, stilbite, analcime, chabazite,thomsonite, heulandite, and others. These species occur of secondaryorigin in the cavities of amygdaloid, basalt, and lava, also, lessfrequently, in granite and gneiss. So called because many of thesespecies intumesce before the blowpipe. Needle zeolite, needlestone;natrolite.",
        "ZEOLITIC": "Of or pertaining to a zeolite; consisting of, or resembling, azeolite.",
        "ZEOLITIFORM": "Having the form of a zeolite.",
        "ZEPHYR": "The west wind; poetically, any soft, gentle breeze. \"Soft thezephyr blows.\" Gray.As gentle As zephyrs blowing below the violet. Shak.Zephyr cloth, a thin kind of cassimere made in Belgium; also, awaterproof fabric of wool.-- Zephyr shawl, a kind of thin, light, embroidered shawl made ofworsted and cotton.-- Zephyr yarn, or worsted, a fine, soft kind of yarn or worsted, --used for knitting and embroidery.",
        "ZEPHYRUS": "The west wind, or zephyr; -- usually personified, and made themost mild and gentle of all the sylvan deities.Mild as when Zephyrus on Flora breathes. Milton.",
        "ZEPPELIN": "A dirigible balloon of the rigid type, consisting of acylindrical trussed and covered frame supported by internal gascells, and provided with means of propulsion and  control. It wasfirst successfully used by Ferdinand Count von Zeppelin.",
        "ZEQUIN": "See Sequin.",
        "ZERDA": "The fennec.",
        "ZERIBA": "Same as Zareba.",
        "ZERO": "A cipher; nothing; naught.",
        "ZETA": "A Greek letter [z] corresponding to our z.",
        "ZETETIC": "Seeking; proceeding by inquiry. Zetetic method (Math.), themethod used for finding the value of unknown quantities by directsearch, in investigation, or in the solution of problems. [R.]Hutton.",
        "ZETETICS": "A branch of algebra which relates to the direct search forunknown quantities. [R.]",
        "ZEUGLODON": "A genus of extinct Eocene whales, remains of which have beenfound in the Gulf States. The species had very long and slenderbodies and broad serrated teeth. See Phocodontia.",
        "ZEUGLODONT": "Any species of Zeuglodonta.",
        "ZEUGLODONTA": "Same as Phocodontia.",
        "ZEUGMA": "A figure by which an adjective or verb, which agrees with anearer word, is, by way of supplement, referred also to another moreremote; as, \"hic illius arma, hic currus fuit;\" where fuit, whichagrees directly with currus, is referred also to arma.",
        "ZEUGMATIC": "Of or pertaining to zeugma; characterized by zeugma.",
        "ZEUGOBRANCHIATA": "Same as Zygobranchia.",
        "ZEUS": "The chief deity of the Greeks, and ruler of the upper world(cf. Hades). He was identified with Jupiter.",
        "ZEUZERIAN": "Any one of a group of bombycid moths of which the genus Zeuzerais the type. Some of these moths are of large size. The goat moth isan example.",
        "ZEYLANITE": "See Ceylanite.",
        "ZIEGA": "Curd produced from milk by adding acetic acid, after rennet hasceased to cause coagulation. Brande & C.",
        "ZIETRISIKITE": "A mineral wax, vert similar to ozocerite. It is found atZietrisika, Moldavia, whence its name.",
        "ZIF": "The second month of the Jewish ecclesiastical year,corresponding to our May.",
        "ZIGZAG": "A molding running in a zigzag line; a chevron, or series ofchevrons. See Illust. of Chevron, 3.",
        "ZIGZAGGERY": "The quality or state of being zigzag; crookedness. [R.]The . . . zigzaggery of my father's approaches. Sterne.",
        "ZIGZAGGY": "Having sharp turns. Barham.",
        "ZIKKURAT": "A temple tower of the Babylonians or Assyrians, consisting of alofty pyramidal structure, built in successive stages, with outsidestaircases, and a shrine at the top.",
        "ZILLA": "A low, thorny, suffrutescent, crucifeous plant (Zillamyagroides) found in the deserts of Egypt. Its leaves are boiled inwater, and eaten, by the Arabs.",
        "ZILLAH": "A district or local division, as of a province. [India]",
        "ZIMB": "A large, venomous, two-winged fly, native of Abyssinia. It isallied to the tsetse fly, and, like the latter, is destructive tocattle.",
        "ZIMENT-WATER": "A kind of water found in copper mines; water impregnated withcopper.",
        "ZIMOCCA": "A sponge (Euspongia zimocca) of flat form and fine quality,from the Adriatic, about the Greek islands, and the coast of Barbary.",
        "ZINC": "An abundant element of the magnesium-cadmium group, extractedprincipally from the minerals zinc blende, smithsonite, calamine, andfranklinite, as an easily fusible bluish white metal, which ismalleable, especially when heated. It is not easily oxidized in moistair, and hence is used for sheeting, coating galvanized iron, etc. Itis used in making brass, britannia, and other alloys, and is alsolargely consumed in electric batteries. Symbol Zn. Atomic weight 64.9[Formerly written also zink.] Butter of zinc (Old Chem.), zincchloride, ZnCl2, a deliquescent white waxy or oily substance.-- Oxide of zinc. (Chem.) See Zinc oxide, below.-- Zinc amine (Chem.), a white amorphous substance, Zn(NH2)2,obtained by the action of ammonia on zinc ethyl; -- called also zincamide.-- Zinc amyle (Chem.), a colorless, transparent liquid, composed ofzinc and amyle, which, when exposed to the atmosphere, emits fumes,and absorbs oxygen with rapidity.-- Zinc blende Etym: [cf. G. zinkblende] (Min.), a native zincsulphide. See Blende, n. (a) -- Zinc bloom Etym: [cf. G. zinkblumenflowers of zinc, oxide of zinc] (Min.), hydrous carbonate of zinc,usually occurring in white earthy incrustations; -- called alsohydrozincite.-- Zinc ethyl (Chem.), a colorless, transparent, poisonous liquid,composed of zinc and ethyl, which takes fire spontaneously onexposure to the atmosphere.-- Zinc green, a green pigment consisting of zinc and cobalt oxides;-- called also Rinmann's green.-- Zinc methyl (Chem.), a colorless mobile liquid Zn(CH3)2, producedby the action of methyl iodide on a zinc sodium alloy. It has adisagreeable odor, and is spontaneously inflammable in the air. Ithas been of great importance in the synthesis of organic compounds,and is the type of a large series of similar compounds, as zincethyl, zinc amyle, etc.-- Zinc oxide (Chem.), the oxide of zinc, ZnO, forming a lightfluffy sublimate when zinc is burned; -- called also flowers of zinc,philosopher's wool, nihil album, etc. The impure oxide produced byburning the metal, roasting its ores, or in melting brass, is calledalso pompholyx, and tutty.-- Zinc spinel (Min.), a mineral, related to spinel, consistingessentially of the oxides of zinc and aluminium; gahnite.-- Zinc vitriol (Chem.), zinc sulphate. See White vitriol, underVitriol.-- Zinc white, a white powder consisting of zinc oxide, used as apigment.",
        "ZINCANE": "Zinc chloride. [Obs.]",
        "ZINCIC": "Pertaining to, containing, or resembling, zinc; zincous.",
        "ZINCIDE": "A binary compound of zinc. [R.]",
        "ZINCIFEROUS": "Containing or affording zinc.",
        "ZINCIFICATION": "The act or process of applying zinc; the condition of beingzincified, or covered with zinc; galvanization.",
        "ZINCIFY": "To coat or impregnate with zinc.",
        "ZINCITE": "Native zinc oxide; a brittle, translucent mineral, of anorange-red color; -- called also red zinc ore, and red oxide of zinc.",
        "ZINCKY": ", Pertaining to zinc, or having its appearance. [Written alsozinky.]",
        "ZINCO-": "A combining form from zinc; in chemistry, designating zinc asan element of certain double compounds. Also used adjectively.",
        "ZINCO-POLAR": "Electrically polarized like the surface of the zinc presentedto the acid in a battery, which has zincous affinity. [Obs.]",
        "ZINCODE": "The positive electrode of an electrolytic cell; anode. [R.]Miller.",
        "ZINCOGRAPH": "A zinc plate prepared for printing by zincography; also, aprint from such a plate.",
        "ZINCOGRAPHER": "Am engraver on zinc.",
        "ZINCOGRAPHY": "The art or process of engraving or etching on zinc, in whichthe design is left in relief in the style of a wood cut, the rest ofthe ground being eaten away by acid.",
        "ZINCOID": "Pertaining to, or resembling, zinc; -- said of the electricityof the zincous plate in connection with a copper plate in a voltaiccircle; also, designating the positive pole. [Obs.]",
        "ZINCOUS": "Of or pertaining to the positive pole of a galvanic battery;electro-positive.",
        "ZINGARO": "A gypsy.",
        "ZINGEL": "A small, edible, freshwater European perch (Aspro zingel),having a round, elongated body and prominent snout.",
        "ZINGIBERACEOUS": "Of or pertaining to ginger, or to a tribe (Zingibereæ) ofendogenous plants of the order Scitamineæ. See Scitamineous.",
        "ZINK": "See Zinc. [Obs.]",
        "ZINKENITE": "A steel-gray metallic mineral, a sulphide of antimony and lead.",
        "ZINKY": "See Zincky. Kirwan.",
        "ZINNIA": "Any plant of the composite genus Zinnia, Mexican herbs withopposite leaves and large gay-colored blossoms. Zinnia elegans is thecommonest species in cultivation.",
        "ZINNWALDITE": "A kind of mica containing lithium, often associated with tinore.",
        "ZINSANG": "The delundung.",
        "ZINZIBERACEOUS": "Same as Zingiberaceous.",
        "ZION": "A hill in Jerusalem, which, after the capture of that city bythe Israelites, became the royal residence of David and hissuccessors.",
        "ZIONISM": "Among the Jews, a theory, plan, or movement for colonizingtheir own race in Palestine, the land of Zion, or, if that isimpracticable, elsewhere, either for religious or nationalizingpurposes; -- called also Zion movement. --Zi\"on*ist, n. --Zi`on*is\"tic (#), a.",
        "ZIP": "A hissing or sibilant sound such as that made by a flyingbullet.",
        "ZIPHIOID": "See Xiphioid.",
        "ZIRCO-": "A combining form (also used adjectively) designating zirconiumas an element of certain double compounds; zircono-; as inzircofluoric acid, sodium zircofluoride.",
        "ZIRCOFLUORIDE": "A double fluoride of zirconium and hydrogen, or some otherpositive element or radical; as, zircofluoride of sodium.",
        "ZIRCON": "A mineral occurring in tetragonal crystals, usually of a brownor gray color. It consists of silica and zirconia. A red variety,used as a gem, is called hyacinth. Colorless, pale-yellow or smoky-brown varieties from Ceylon are called jargon. Zircon syenite, acoarse-grained syenite containing zircon crystals and often alsoelæolite. It is largely developed in Southern Norway.",
        "ZIRCON LIGHT": "A light, similar to the calcium light, produced by incandescentzirconia.",
        "ZIRCONA": "Zirconia.",
        "ZIRCONATE": "A salt of zirconic acid.",
        "ZIRCONIA": "The oxide of zirconium, obtained as a white powder, andpossessing both acid and basic properties. On account of itsinfusibility, and brilliant luminosity when incandescent, it is usedas an ingredient of sticks for the Drummomd light.",
        "ZIRCONIC": "Pertaining to, containing, or resembling, zirconium; as,zirconic oxide; zirconic compounds. Zirconic acid, an acid ofzirconium analogous to carbonic and silicic acids, known only in itssalts.",
        "ZIRCONIUM": "A rare element of the carbon-silicon group, intermediatebetween the metals and nonmetals, obtained from the mineral zircon asa dark sooty powder, or as a gray metallic crystalline substance.Symbol Zr. Atomic weight, 90.4.",
        "ZIRCONO": "See Zirco-.",
        "ZIRCONOID": "A double eight-sided pyramid, a form common with tetragonalcrystals; -- so called because this form often occurs in crystals ofzircon.",
        "ZITHER": "An instrument of music used in Austria and Germany. It has fromthirty to forty wires strung across a shallow sounding-board, whichlies horizontally on a table before the performer, who uses bothhands in playing on it.",
        "ZITTERN": "See Cittern.",
        "ZIZANIA": "A genus of grasses including Indian rice. See Indian rice,under Rice.",
        "ZIZEL": "The suslik. [Written also zisel.]",
        "ZIZITH": "The tassels of twisted cords or threads on the corners of theupper garment worn by strict Jews. The Hebrew for this word istranslated in both the Authorized and Revised Versions (Deut. xxii.12) by the word \"fringes.\"",
        "ZOANTHACEA": "A suborder of Actinaria, including Zoanthus and allied genera,which are permanently attached by their bases.",
        "ZOANTHARIA": "Same as Anthozoa.",
        "ZOANTHARIAN": "Of or pertaining to the Zoantharia.-- n.",
        "ZOANTHODEME": "The zooids of a compound anthozoan, collectively.",
        "ZOANTHOID": "Of or pertaining to the Zoanthacea.",
        "ZOANTHROPY": "A kind of monomania in which the patient believes himselftransformed into one of the lower animals.",
        "ZOANTHUS": "A genus of Actinaria, including numerous species, found mostlyin tropical seas. The zooids or polyps resemble small, elongatedactinias united together at their bases by fleshy stolons, and thusforming extensive groups. The tentacles are small and bright colored.",
        "ZOBO": "A kind of domestic cattle reared in Asia for its flesh andmilk. It is supposed to be a hybrid between the zebu and the yak.",
        "ZOCLE": "Same as Socle.",
        "ZODIACAL": "Of or pertaining to the zodiac; situated within the zodiac; as,the zodiacal planets. Zodiacal light, a luminous tract of the sky, ofan elongated, triangular figure, lying near the ecliptic, its basebeing on the horizon, and its apex at varying altitudes. It is to beseen only in the evening, after twilight, and in the morning beforedawn. It is supposed to be due to sunlight reflected from multitudesof meteoroids revolving about the sun nearly in the plane of theecliptic.",
        "ZOEA": "A peculiar larval stage of certain decapod Crustacea,especially of crabs and certain Anomura. [Written also zoæa.]",
        "ZOETROPE": "An optical toy, in which figures made to revolve on the insideof a cylinder, and viewed through slits in its circumference, appearlike a single figure passing through a series of natural motions asif animated or mechanically moved.",
        "ZOHAR": "A Jewish cabalistic book attributed by tradition to Rabbi Simonben Yochi, who lived about the end of the 1st century, a. d. Moderncritics believe it to be a compilation of the 13th century. Encyc.Brit.",
        "ZOIC": "Of or pertaining to animals, or animal life.",
        "ZOIDE": "See Meride.",
        "ZOILEAN": "Having the characteristic of Zoilus, a bitter, envious, unjustcritic, who lived about 270 years before Christ.",
        "ZOILISM": "Resemblance to Zoilus in style or manner; carping criticism;detraction.Bring candid eyes the perusal of men's works, and let not Zoilism ordetraction blast well-intended labors. Sir T. Browne.",
        "ZOISITE": "A grayish or whitish mineral occurring in orthorhombic,prismatic crystals, also in columnar masses. It is a silicate ofalumina and lime, and is allied to epidote.",
        "ZOKOR": "An Asiatic burrowing rodent (Siphneus aspalax) resembling themole rat. It is native of the Altai Mountains.",
        "ZOLAESQUE": "In the style of Zola (see Zolaism).",
        "ZOLAISM": "The literary theories and practices of the French novelistEmile Zola (1840-1902); naturalism, esp. in a derogatory sense. --Zo\"la*ist, n. -- Zo`la*is\"tic (#), a. -- Zo\"la*ize (#), v.",
        "ZOLLVEREIN": "Literally, a customs union; specifically, applied to theseveral customs unions successively formed under the leadership ofPrussia among certain German states for establishing liberty ofcommerce among themselves and common tariff on imports, exports, andtransit.",
        "ZOMBORUK": "See Zumbooruk.",
        "ZONA": "A zone or band; a layer. Zona pellucida. Etym: [NL.] (Biol.)(a) The outer transparent layer, or envelope, of the ovum. It is amore or less elastic membrane with radiating striæ, and correspondsto the cell wall of an ordinary cell. See Ovum, and Illust. ofMicroscope. (b) The zona radiata.-- Zona radiata Etym: [NL.] (Biol.), a radiately striated membranesituated next the yolk of an ovum, or separated from it by a verydelicate membrane only.",
        "ZONAL": "Of or pertaining to a zone; having the form of a zone or zones.Zonal equation (Crystallog.), the mathematical relation which belongsto all the planes of a zone, and expresses their common position withreference to the axes.-- Zonal structure (Crystallog.), a structure characterized by thearrangements of color, inclusions, etc., of a crystal in parallel orconcentric layers, which usually follow the outline of the crystal,and mark the changes that have taken place during its growth.-- Zonal symmetry. (Biol.) See the Note under Symmetry.",
        "ZONAR": "A belt or girdle which the Christians and Jews of the Levantwere obliged to wear to distinguish them from Mohammedans. [Writtenalso zonnar.]",
        "ZONARIA": "A division of Mammalia in which the placenta is zonelike.",
        "ZONATE": "Divided by parallel planes; as, zonate tetraspores, found incertain red algæ.",
        "ZONE": "One of the five great divisions of the earth, with respect tolatitude and temperature.",
        "ZONED": "Zonate.",
        "ZONELESS": "Not having a zone; ungirded.The reeling goddess with the zoneless waist. Cowper.In careless folds, loose fell her zoneless vest. Mason.",
        "ZONNAR": "See Zonar.",
        "ZONULAR": "Of or pertaining to a zone; zone-shaped. \"The zonular type of aplacenta.\" Dana.",
        "ZONULE": "A little zone, or girdle.",
        "ZONULET": "A zonule. Herrick.",
        "ZONURE": "Any one of several of South African lizards of the genusZonura, common in rocky situations.",
        "ZOOECIUM": "One of the cells or tubes which inclose the feeling zooids ofBryozoa. See Illust. of Sea Moss.",
        "ZOOID": "Pertaining to, or resembling, an animal.",
        "ZOOIDAL": "Of or pertaining to a zooid; as, a zooidal form.",
        "ZOOLOGIZE": "To study zoölogy; esp., to collect animals for study.",
        "ZOOZOO": "The wood pigeon. [Prov. Eng.]",
        "ZOPE": "A European fresh-water bream (Abramis ballerus).",
        "ZOPILOTE": "The urubu, or American black vulture.",
        "ZORIL": "Same as Zorilla.",
        "ZORILLA": "Either one of two species of small African carnivores of thegenus Ictonyx allied to the weasels and skunks. [Written also zoril,and zorille.]",
        "ZOROASTRIAN": "Of or pertaining to Zoroaster, or his religious system.",
        "ZOROASTRIANISM": "The religious system of Zoroaster, the legislator and prophetof the ancient Persians, which was the national faith of Persia;mazdeism. The system presupposes a good spirit (Ormuzd) and anopposing evil spirit (Ahriman). Cf. Fire worship, under Fire, andParsee.",
        "ZOROASTRISM": "Same as Zoroastrianism. Tylor.",
        "ZOSTER": "Shingles.",
        "ZOSTERA": "A genus of plants of the Naiadaceæ, or Pondweed family. Zosteramarina is commonly known as sea wrack, and eelgrass.",
        "ZOSTEROPS": "A genus of birds that comprises the white-eyes. See White-eye.",
        "ZOUNDS": "An exclamation formerly used as an oath, and an expression ofanger or wonder.",
        "ZOUTCH": "To stew, as flounders, eels, etc., with just enough or liquidto cover them. Smart.",
        "ZUBR": "The aurochs.",
        "ZUCHE": "A stump of a tree. Cowell.",
        "ZUCHETTO": "A skullcap covering the tonsure, worn under the berretta. Thepope's is white; a cardinal's red; a bishop's purple; a priest'sblack.",
        "ZUFOLO": "A little flute or flageolet, especially that which is used toteach birds. [Written also zuffolo.]",
        "ZUIAN": "Of or pert. to the Zuñis, or designating their linguisticstock. --n.",
        "ZUISIN": "The American widgeon. [Local, U. S.]",
        "ZULU-KAFFIR": "A member of the Bantu race comprising the Zulus and theKaffirs.",
        "ZULUS": "The most important tribe belonging to the Kaffir race. Theyinhabit a region on the southeast coast of Africa, but formerlyoccupied a much more extensive country. They are noted for theirwarlike disposition, courage, and military skill.",
        "ZUMBOORUK": "A small cannon supported by a swiveled rest on the back of acamel, whence it is fired, -- used in the East.",
        "ZUNIS": "A tribe of Pueblo Indians occupying a village in New Mexico, onthe Zuni River.",
        "ZUNYITE": "A fluosilicate of alumina occurring in tetrahedral crystals atthe Zuñi mine in Colorado.",
        "ZWANZIGER": "Am Austrian silver coin equivalent to 20 kreutzers, or about 10cents.",
        "ZWIEBACK": "A kind of biscuit or  rusk first baked in a loaf and afterwardscut and toasted.",
        "ZWINGLIAN": "Of or pertaining to Ulric Zwingli (1481-1531), the reformer ofGerman Switzerland, who maintained that in the Lord's Supper the truebody of Christ is present by the contemplation of faith but not inessence or reality, and that the sacrament is a memorial withoutmystical elements. -- n.",
        "ZYGANTRUM": "See under Zygosphene.",
        "ZYGAPOPHYSIS": "One of the articular processes of a vertebra, of which thereare usually four, two anterior and two posterior. See under Vertebra.-- Zyg`ap*o*phys\"i*al, a.",
        "ZYGENID": "Any one of numerous species of moths of the family Zygænidæ,most of which are bright colored. The wood nymph and the vineforester are examples. Also used adjectively.",
        "ZYGOBRANCHIA": "A division of marine gastropods in which the gills aredeveloped on both sides of the body and the renal organs are alsopaired. The abalone (Haliotis) and the keyhole limpet (Fissurella)are examples.",
        "ZYGOBRANCHIATE": "Of or pertaining to the Zygobranchia.",
        "ZYGODACTYLAE": "The zygodactylous birds. In a restricted sense applied to adivision of birds which includes the barbets, toucans, honey guides,and other related birds.",
        "ZYGODACTYLI": "Same as Scansores.",
        "ZYGOMATIC": "Of, pertaining to, or in the region of, the zygoma. Zygomaticarch, the arch of bone beneath the orbit, formed in most mammals bythe union of the malar, or jugal, with the zygomatic process of thetemporal bone. In the lower vertebrates other bones may help to formit, and there may be two arches on each side of the skull, as in somereptiles.-- Zygomatic process, a process of the temporal or squamosal bonehelping to form the zygomatic arch.",
        "ZYGOPHYTE": "Any plant of a proposed class or grand division (Zygophytes,Zygophyta, or Zygosporeæ), in which reproduction consists in theunion of two similar cells. Cf. Oöphyte.",
        "ZYGOSIS": "Same as Conjugation.",
        "ZYGOSPERM": "A spore formed by the union of the contents of two similarcells, either of the same or of distinct individual plants.Zygosperms are found in certain orders of algæ and fungi.",
        "ZYGOSPHENE": "A median process on the front part of the neural arch of thevertebræ of most snakes and some lizards, which fits into a fossa,called the zygantrum, on the back part of the arch in front.",
        "ZYLONITE": "Celluloid.",
        "ZYMASE": "A soluble ferment, or enzyme. See Enzyme.",
        "ZYME": "The morbific principle of a zymotic disease. Quain.",
        "ZYMIC": "Pertaining to, or produced by, fermentation; -- formerly, byconfusion, used to designate lactic acid.",
        "ZYMOGEN": "A mother substance, or antecedent, of an enzyme or chemicalferment; -- applied to such substances as, not being themselvesactual ferments, may by internal changes give rise to a ferment.The pancreas contains but little ready-made ferment, though there ispresent in it a body, zymogen, which gives birth to the ferment.Foster.",
        "ZYMOGENE": "One of a physiological group of globular bacteria whichproduces fermentations of diverse nature; -- distinguished frompathogene.",
        "ZYMOGENIC": "Of or pertaining to zymology.",
        "ZYMOLOGIST": "One who is skilled in zymology, or in the fermentation ofliquors.",
        "ZYMOLOGY": "A treatise on the fermentation of liquors, or the doctrine offermentation. [Written also zumology.]",
        "ZYMOLYSIS": "The action of enzymes; also, the changes produced by suchaction. --Zy`mo*lyt\"ic (#), a.",
        "ZYMOME": "A glutinous substance, insoluble in alcohol, resemblinglegumin; -- now called vegetable fibrin, vegetable albumin, or glutencasein.",
        "ZYMOPHYTE": "A bacteroid ferment.",
        "ZYMOSE": "Invertin.",
        "ZYMOTIC": "Designating, or pertaining to, a certain class of diseases. SeeZymotic disease, below. Zymotic disease (Med.), any epidemic,endemic, contagious, or sporadic affection which is produced by somemorbific principle or organism acting on the system like a ferment.",
        "ZYTHEM": "See Zythum.",
        "ZYTHEPSARY": "A brewery. [R.]"
    };
}